-- ==============================================================================
-- ELEGANCE MAKEOVER & ACADEMY - COMPLETE MASTER SUPABASE SCHEMA & SEO ENGINE
-- File: docs/schema.sql
-- Description: Unified, standalone, 100% idempotent SQL schema for Supabase.
--              Includes core business entities, bookings, audit logs, CMS tables,
--              SEO metadata, 8 services, 10 local service areas, 12 cornerstone
--              blog posts, analytical views, triggers, and Row Level Security (RLS).
-- ==============================================================================

-- ==============================================================================
-- 0. UTILITIES & EXTENSIONS
-- ==============================================================================

create extension if not exists pgcrypto;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ==============================================================================
-- 1. CORE AUTH & USER MANAGEMENT
-- ==============================================================================

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(191) not null unique,
  password_hash varchar(255) default '',
  role text not null default 'admin' check (role in ('admin', 'manager', 'staff')),
  last_login timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.users
  alter column password_hash drop not null;
alter table public.users
  alter column password_hash set default '';

create unique index if not exists idx_users_email
  on public.users (email)
  where deleted_at is null;

drop trigger if exists trigger_users_touch_updated_at on public.users;
create trigger trigger_users_touch_updated_at
before update on public.users
for each row
execute function public.touch_updated_at();

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  email text not null unique,
  role text not null default 'editor' check (role in ('super_admin', 'admin', 'editor')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_admin_users_email
  on public.admin_users (email);
create index if not exists idx_admin_users_auth_user_id
  on public.admin_users (auth_user_id);
create index if not exists idx_admin_users_role
  on public.admin_users (role);
create index if not exists idx_admin_users_active
  on public.admin_users (is_active);

drop trigger if exists trigger_admin_users_touch_updated_at on public.admin_users;
create trigger trigger_admin_users_touch_updated_at
before update on public.admin_users
for each row
execute function public.touch_updated_at();

insert into public.admin_users (auth_user_id, email, role, is_active, created_at, updated_at)
values
  (null, 'elegancemakeover.2021@gmail.com', 'super_admin', true, now(), now())
on conflict (email) do update set
  role = excluded.role,
  is_active = true,
  updated_at = now();

-- ==============================================================================
-- 2. SERVICES (CORE & SEO ENHANCED)
-- ==============================================================================

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  slug varchar(160),
  title varchar(160) not null,
  category text not null check (category in ('bridal', 'parlour', 'academy')),
  description text not null,
  price_label varchar(64) not null,
  price_min numeric(10,2),
  price_max numeric(10,2),
  duration_label varchar(64) not null,
  duration_minutes int,
  featured boolean not null default false,
  image_url varchar(255),
  meta_title varchar(160),
  meta_description text,
  og_image varchar(255),
  faq_json jsonb default '[]'::jsonb,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.services
  add column if not exists slug varchar(160),
  add column if not exists meta_title varchar(160),
  add column if not exists meta_description text,
  add column if not exists og_image varchar(255),
  add column if not exists faq_json jsonb default '[]'::jsonb;

-- Populate default slugs for any pre-existing services
update public.services set slug = 'bridal-makeup' where slug is null and lower(title) like '%bridal%' and lower(title) not like '%airbrush%';
update public.services set slug = 'hd-airbrush-bridal-makeup' where slug is null and lower(title) like '%airbrush%';
update public.services set slug = 'engagement-makeup' where slug is null and lower(title) like '%engagement%';
update public.services set slug = 'party-makeup' where slug is null and lower(title) like '%party%';
update public.services set slug = 'hair-styling' where slug is null and lower(title) like '%hair%' and lower(title) not like '%smoothen%';
update public.services set slug = 'hydra-facial' where slug is null and (lower(title) like '%facial%' or lower(title) like '%hydra%');
update public.services set slug = 'hair-smoothening' where slug is null and lower(title) like '%smoothen%';
update public.services set slug = 'makeup-academy-course' where slug is null and (lower(title) like '%academy%' or lower(title) like '%course%');
update public.services set slug = 'service-' || id where slug is null;

-- Deduplicate any duplicate slugs before unique indexing
with duplicates as (
  select id, row_number() over (partition by slug order by id) as rnum
  from public.services
  where slug is not null
)
update public.services s
set slug = s.slug || '-' || s.id
from duplicates d
where s.id = d.id and d.rnum > 1;

-- Drop legacy partial index/constraint and create unconditional unique index for ON CONFLICT
alter table public.services drop constraint if exists services_slug_key;
drop index if exists public.idx_services_slug;
create unique index if not exists idx_services_slug on public.services (slug);

create index if not exists idx_services_category
  on public.services (category)
  where deleted_at is null;
create index if not exists idx_services_active
  on public.services (is_active)
  where deleted_at is null;
create index if not exists idx_services_sort_order
  on public.services (sort_order);

drop trigger if exists trigger_services_touch_updated_at on public.services;
create trigger trigger_services_touch_updated_at
before update on public.services
for each row
execute function public.touch_updated_at();

-- Seed 8 Signature Services with Full SEO Data
insert into public.services (
  slug, title, category, description, price_label, price_min, price_max,
  duration_label, duration_minutes, featured, meta_title, meta_description, is_active, sort_order
)
values
  (
    'bridal-makeup',
    'Bridal Makeup',
    'bridal',
    'Signature bespoke bridal makeover blending modern luxury HD cosmetics with authentic Odia traditions, mukut balancing, and ceremonial longevity.',
    '₹8,000 - ₹12,000',
    8000, 12000,
    '3 - 3.5 Hours',
    210,
    true,
    'Bridal Makeup Artist in Jajpur Road | Elegance Makeover',
    'Award-winning bridal makeup in Jajpur Road, Odisha by Rasmirekha Swain. Traditional Odia bridal styling, mukut fitting & 16-hr waterproof HD artistry.',
    true,
    1
  ),
  (
    'hd-airbrush-bridal-makeup',
    'HD Airbrush Bridal Makeup',
    'bridal',
    'Flawless micro-spray silicone airbrush formulation engineered for high-humidity coastal climates, tear-resistance, and 4K wedding cinematography.',
    '₹12,000 - ₹16,000',
    12000, 16000,
    '3.5 - 4 Hours',
    240,
    true,
    'HD Airbrush Bridal Makeup in Odisha | 24-Hr Waterproof',
    'Premier HD Airbrush bridal makeup in Odisha by Master Artist Rasmirekha Swain. 100% waterproof, sweatproof, and camera-ready 4K high-definition finish.',
    true,
    2
  ),
  (
    'engagement-makeup',
    'Engagement & Ring Ceremony Makeup',
    'bridal',
    'Soft-glam radiant makeover designed for evening lighting, ring exchanges, and engagement photography with bespoke hair and floral accents.',
    '₹5,000 - ₹8,000',
    5000, 8000,
    '2 - 2.5 Hours',
    150,
    true,
    'Engagement Makeup Artist in Jajpur Road | Ring Ceremony Glam',
    'Elegant engagement makeup in Jajpur Road, Odisha. Soft-glam glowing base, bespoke hair styling & custom lash extensions by Master Artist Rasmirekha.',
    true,
    3
  ),
  (
    'party-makeup',
    'Party & Reception Makeup',
    'parlour',
    'High-impact celebrity glam for bridesmaids, wedding guests, reception parties, and festive celebrations with long-wear finish.',
    '₹3,000 - ₹5,000',
    3000, 5000,
    '1.5 - 2 Hours',
    100,
    false,
    'Party Makeup in Jajpur Road | Sangeet & Reception Glam',
    'Glamorous party and reception makeup in Jajpur Road, Odisha. Long-lasting HD base, smoky eyes, and contemporary hair design for wedding guests.',
    true,
    4
  ),
  (
    'hair-styling',
    'Bridal & Event Hair Styling',
    'parlour',
    'Bespoke hair design from classical jasmine gajra buns with mukut anchors to textured modern Hollywood waves and floral braid artistry.',
    '₹1,500 - ₹3,500',
    1500, 3500,
    '1 - 1.5 Hours',
    75,
    false,
    'Bridal Hair Styling in Jajpur Road | Gajra & Modern Buns',
    'Professional bridal hair styling in Jajpur Road, Odisha. Classic Odia bridal buns, fresh jasmine gajra placement, mukut anchoring & reception waves.',
    true,
    5
  ),
  (
    'hydra-facial',
    'Clinical Hydra Glow Facial',
    'parlour',
    'Medical-grade vortex extraction and dermal infusion treatment designed to unclog pores, eliminate blackheads, and hydrate skin for an instant bridal glow.',
    '₹2,500 - ₹4,500',
    2500, 4500,
    '60 - 75 Mins',
    60,
    false,
    'Hydra Facial in Jajpur Road | Instant Glass Skin Glow',
    'Medical-grade Hydra Facial in Jajpur Road, Odisha. Deep pore vacuum extraction, antioxidant infusion & deep barrier hydration for brides and clients.',
    true,
    6
  ),
  (
    'hair-smoothening',
    'Hair Smoothening & Keratin',
    'parlour',
    'Formaldehyde-free salon treatment providing mirror-shine, frizz-free straightness, and thermal protection lasting 6 to 9 months.',
    '₹4,500 - ₹8,500',
    4500, 8500,
    '3 - 4 Hours',
    210,
    false,
    'Hair Smoothening & Keratin in Jajpur Road | Frizz-Free Shine',
    'Professional hair smoothening, keratin & nanoplastia in Jajpur Road, Odisha. Long-lasting silky straight hair with salon-grade nourishment.',
    true,
    7
  ),
  (
    'makeup-academy-course',
    'Professional Makeup Artist Course',
    'academy',
    'Comprehensive master certification program with live model practice, vanity lighting mastery, bridal draping, and business client development.',
    '₹35,000 - ₹50,000',
    35000, 50000,
    '6 - 12 Weeks',
    4800,
    true,
    'Makeup Artist Academy Course in Odisha | Certification',
    'Government-certified professional makeup artist course in Jajpur Road, Odisha. Learn bridal HD, airbrush, hairstyling & business skills from Rasmirekha.',
    true,
    8
  )
on conflict (slug) do update set
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  price_label = excluded.price_label,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  duration_label = excluded.duration_label,
  duration_minutes = excluded.duration_minutes,
  featured = excluded.featured,
  updated_at = now();

-- ==============================================================================
-- 3. GALLERY, TESTIMONIALS, OFFERS, ADS
-- ==============================================================================

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  category text not null check (category in ('bridal', 'parlour', 'before_after', 'academy')),
  image_url varchar(255) not null,
  alt_text varchar(255) not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_gallery_category
  on public.gallery (category)
  where deleted_at is null;
create index if not exists idx_gallery_active
  on public.gallery (is_active)
  where deleted_at is null;
create index if not exists idx_gallery_sort_order
  on public.gallery (sort_order);

drop trigger if exists trigger_gallery_touch_updated_at on public.gallery;
create trigger trigger_gallery_touch_updated_at
before update on public.gallery
for each row
execute function public.touch_updated_at();

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  customer_name varchar(120) not null,
  customer_email varchar(191),
  service_name varchar(160) not null,
  rating smallint not null check (rating between 1 and 5),
  review_text text not null,
  status text not null default 'visible' check (status in ('visible', 'draft', 'archived')),
  booking_id bigint,
  wedding_month_year varchar(60),
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_testimonials_status
  on public.testimonials (status)
  where deleted_at is null;
create index if not exists idx_testimonials_rating
  on public.testimonials (rating)
  where deleted_at is null;

drop trigger if exists trigger_testimonials_touch_updated_at on public.testimonials;
create trigger trigger_testimonials_touch_updated_at
before update on public.testimonials
for each row
execute function public.touch_updated_at();

create table if not exists public.offers (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  discount_label varchar(64) not null,
  discount_percentage smallint check (discount_percentage between 0 and 100),
  description text not null,
  valid_from date not null,
  valid_until date not null,
  status text not null default 'scheduled' check (status in ('scheduled', 'active', 'expired', 'paused')),
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_offers_status_dates
  on public.offers (status, valid_from, valid_until)
  where deleted_at is null;

drop trigger if exists trigger_offers_touch_updated_at on public.offers;
create trigger trigger_offers_touch_updated_at
before update on public.offers
for each row
execute function public.touch_updated_at();

create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  asset_url varchar(255) not null,
  asset_type text not null default 'poster' check (asset_type in ('poster', 'banner', 'carousel', 'story')),
  platform text default 'website' check (platform in ('website', 'instagram', 'facebook', 'whatsapp')),
  start_date date not null,
  end_date date not null,
  status text not null default 'active' check (status in ('active', 'paused', 'archived', 'scheduled')),
  impressions int not null default 0,
  clicks int not null default 0,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_advertisements_status_dates
  on public.advertisements (status, start_date, end_date)
  where deleted_at is null;

drop trigger if exists trigger_advertisements_touch_updated_at on public.advertisements;
create trigger trigger_advertisements_touch_updated_at
before update on public.advertisements
for each row
execute function public.touch_updated_at();

-- ==============================================================================
-- 4. BOOKINGS & INQUIRIES
-- ==============================================================================

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_code varchar(32) not null unique,
  customer_name varchar(120) not null,
  phone varchar(32) not null,
  email varchar(191),
  service_id bigint references public.services(id) on delete set null,
  service_name varchar(160) not null,
  booking_date date not null,
  booking_time varchar(32) not null,
  duration_minutes int,
  notes text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'rescheduled', 'completed', 'cancelled')),
  source text not null default 'website' check (source in ('website', 'whatsapp', 'call', 'walk_in', 'instagram')),
  amount_quoted numeric(10,2),
  amount_paid numeric(10,2),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'partial', 'paid', 'refunded')),
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_bookings_date_status
  on public.bookings (booking_date, status)
  where deleted_at is null;
create index if not exists idx_bookings_customer_phone
  on public.bookings (phone)
  where deleted_at is null;
create index if not exists idx_bookings_email
  on public.bookings (email)
  where deleted_at is null;
create index if not exists idx_bookings_code
  on public.bookings (booking_code)
  where deleted_at is null;
create index if not exists idx_bookings_created_at
  on public.bookings (created_at desc)
  where deleted_at is null;

drop trigger if exists trigger_bookings_touch_updated_at on public.bookings;
create trigger trigger_bookings_touch_updated_at
before update on public.bookings
for each row
execute function public.touch_updated_at();

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  phone varchar(32) not null,
  email varchar(191),
  service_name varchar(160),
  message text not null,
  status text not null default 'new' check (status in ('new', 'read', 'replied', 'archived')),
  response_notes text,
  replied_at timestamptz,
  replied_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_contact_messages_status
  on public.contact_messages (status)
  where deleted_at is null;
create index if not exists idx_contact_messages_email
  on public.contact_messages (email)
  where deleted_at is null;

drop trigger if exists trigger_contact_messages_touch_updated_at on public.contact_messages;
create trigger trigger_contact_messages_touch_updated_at
before update on public.contact_messages
for each row
execute function public.touch_updated_at();

create table if not exists public.rate_limits (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  endpoint text not null,
  count int not null default 1,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_rate_limits_ip_endpoint
  on public.rate_limits (ip_hash, endpoint);
create index if not exists idx_rate_limits_expires_at
  on public.rate_limits (expires_at);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.admin_users(id) on delete set null,
  action varchar(50) not null,
  resource_type varchar(80) not null default 'unknown',
  resource_id text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_user_id
  on public.audit_logs (user_id);
create index if not exists idx_audit_logs_resource
  on public.audit_logs (resource_type, resource_id);
create index if not exists idx_audit_logs_created_at
  on public.audit_logs (created_at desc);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete set null,
  customer_email varchar(191),
  customer_phone varchar(32),
  notification_type text not null check (notification_type in ('booking_confirmation', 'booking_reminder', 'booking_cancellation', 'status_update', 'offer_promotion')),
  template_name varchar(100) not null,
  channel text not null default 'email' check (channel in ('email', 'sms', 'whatsapp', 'in_app')),
  subject varchar(255),
  body text,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'bounced')),
  retry_count int not null default 0,
  sent_at timestamptz,
  failed_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_notifications_booking_id
  on public.notifications (booking_id);
create index if not exists idx_notifications_status
  on public.notifications (status);
create index if not exists idx_notifications_created_at
  on public.notifications (created_at desc);

drop trigger if exists trigger_notifications_touch_updated_at on public.notifications;
create trigger trigger_notifications_touch_updated_at
before update on public.notifications
for each row
execute function public.touch_updated_at();

create table if not exists public.customer_preferences (
  id bigint generated by default as identity primary key,
  customer_phone varchar(32) not null unique,
  customer_email varchar(191) unique,
  customer_name varchar(120),
  preferred_service varchar(160),
  preferred_time varchar(32),
  preferred_date_day varchar(15),
  preferred_contact_method text not null default 'phone' check (preferred_contact_method in ('phone', 'email', 'sms', 'whatsapp')),
  total_bookings int not null default 0,
  total_spent numeric(10,2) not null default 0,
  loyalty_points int not null default 0,
  last_booking_date date,
  opt_in_promotions boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Ensure customer_phone is unconditionally uniquely indexed for trigger ON CONFLICT
alter table public.customer_preferences drop constraint if exists customer_preferences_customer_phone_key;
drop index if exists public.idx_customer_preferences_phone;
create unique index if not exists idx_customer_preferences_phone
  on public.customer_preferences (customer_phone);
create index if not exists idx_customer_preferences_email
  on public.customer_preferences (customer_email);

drop trigger if exists trigger_customer_preferences_touch_updated_at on public.customer_preferences;
create trigger trigger_customer_preferences_touch_updated_at
before update on public.customer_preferences
for each row
execute function public.touch_updated_at();

create table if not exists public.email_templates (
  id bigint generated by default as identity primary key,
  template_name varchar(100) not null unique,
  subject varchar(255) not null,
  body text not null,
  variables jsonb,
  is_active boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now()
);

create index if not exists idx_email_templates_name
  on public.email_templates (template_name);

drop trigger if exists trigger_email_templates_touch_updated_at on public.email_templates;
create trigger trigger_email_templates_touch_updated_at
before update on public.email_templates
for each row
execute function public.touch_updated_at();

-- ==============================================================================
-- 5. CMS & SETTINGS TABLES
-- ==============================================================================

create table if not exists public.hero_content (
  id bigint generated by default as identity primary key,
  heading text not null default '',
  subtitle text not null default '',
  primary_cta_label text not null default 'Book Appointment',
  primary_cta_url text not null default '/booking',
  secondary_cta_label text not null default 'View Services',
  secondary_cta_url text not null default '/services',
  hero_image_url text,
  hero_image_alt text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_hero_content_touch_updated_at on public.hero_content;
create trigger trigger_hero_content_touch_updated_at
before update on public.hero_content
for each row
execute function public.touch_updated_at();

create table if not exists public.about_content (
  id bigint generated by default as identity primary key,
  headline text not null default '',
  body text not null default '',
  bullet_points jsonb not null default '[]'::jsonb,
  founder_name text not null default '',
  founder_title text not null default '',
  founder_image_url text,
  gallery_image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_about_content_touch_updated_at on public.about_content;
create trigger trigger_about_content_touch_updated_at
before update on public.about_content
for each row
execute function public.touch_updated_at();

create table if not exists public.contact_settings (
  id bigint generated by default as identity primary key,
  phone text not null default '',
  whatsapp text not null default '',
  email text not null default '',
  address text not null default '',
  map_url text not null default '',
  working_hours text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_contact_settings_touch_updated_at on public.contact_settings;
create trigger trigger_contact_settings_touch_updated_at
before update on public.contact_settings
for each row
execute function public.touch_updated_at();

create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  instagram text,
  facebook text,
  youtube text,
  whatsapp text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_social_links_touch_updated_at on public.social_links;
create trigger trigger_social_links_touch_updated_at
before update on public.social_links
for each row
execute function public.touch_updated_at();

create table if not exists public.seo_settings (
  id bigint generated by default as identity primary key,
  meta_title text not null default '',
  meta_description text not null default '',
  keywords text not null default '',
  canonical_url text not null default '',
  og_image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_seo_settings_touch_updated_at on public.seo_settings;
create trigger trigger_seo_settings_touch_updated_at
before update on public.seo_settings
for each row
execute function public.touch_updated_at();

create table if not exists public.pricing_packages (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  price numeric(10,2) not null default 0,
  popular boolean not null default false,
  features_text text not null default '',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- Ensure pricing packages name is unconditionally uniquely indexed for ON CONFLICT
alter table public.pricing_packages drop constraint if exists pricing_packages_name_key;
drop index if exists public.idx_pricing_packages_name;
create unique index if not exists idx_pricing_packages_name
  on public.pricing_packages (name);
create index if not exists idx_pricing_packages_active
  on public.pricing_packages (is_active)
  where deleted_at is null;
create index if not exists idx_pricing_packages_sort_order
  on public.pricing_packages (sort_order)
  where deleted_at is null;

drop trigger if exists trigger_pricing_packages_touch_updated_at on public.pricing_packages;
create trigger trigger_pricing_packages_touch_updated_at
before update on public.pricing_packages
for each row
execute function public.touch_updated_at();

create table if not exists public.faq_sections (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  slug varchar(120) not null unique,
  description text not null,
  items_text text not null default '',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_faq_sections_active
  on public.faq_sections (is_active)
  where deleted_at is null;
create index if not exists idx_faq_sections_sort_order
  on public.faq_sections (sort_order)
  where deleted_at is null;

drop trigger if exists trigger_faq_sections_touch_updated_at on public.faq_sections;
create trigger trigger_faq_sections_touch_updated_at
before update on public.faq_sections
for each row
execute function public.touch_updated_at();

-- ==============================================================================
-- 6. SERVICE AREAS (PROGRAMMATIC LOCAL SEO)
-- ==============================================================================

create table if not exists public.service_areas (
  id bigint generated by default as identity primary key,
  slug varchar(160),
  name varchar(160) not null,
  summary text not null,
  search_intent text,
  highlights_text text default '',
  meta_title varchar(160),
  meta_description text,
  og_image varchar(255),
  faq_json jsonb default '[]'::jsonb,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.service_areas
  add column if not exists slug varchar(160),
  add column if not exists meta_title varchar(160),
  add column if not exists meta_description text,
  add column if not exists og_image varchar(255),
  add column if not exists faq_json jsonb default '[]'::jsonb;

-- Populate slugs for existing records
update public.service_areas set slug = 'jajpur-road' where slug is null and lower(name) like '%jajpur road%';
update public.service_areas set slug = 'vyasanagar' where slug is null and lower(name) like '%vyasanagar%';
update public.service_areas set slug = 'jajpur-town' where slug is null and lower(name) like '%jajpur town%';
update public.service_areas set slug = 'danagadi' where slug is null and lower(name) like '%danagadi%';
update public.service_areas set slug = 'kalinganagar' where slug is null and lower(name) like '%kalinganagar%';
update public.service_areas set slug = 'panikoili' where slug is null and lower(name) like '%panikoili%';
update public.service_areas set slug = 'kuakhia' where slug is null and lower(name) like '%kuakhia%';
update public.service_areas set slug = 'bhadrak' where slug is null and lower(name) like '%bhadrak%';
update public.service_areas set slug = 'cuttack' where slug is null and lower(name) like '%cuttack%';
update public.service_areas set slug = 'bhubaneswar' where slug is null and lower(name) like '%bhubaneswar%';
update public.service_areas set slug = 'area-' || id where slug is null;

-- Deduplicate any duplicate slugs before unique indexing
with duplicates as (
  select id, row_number() over (partition by slug order by id) as rnum
  from public.service_areas
  where slug is not null
)
update public.service_areas sa
set slug = sa.slug || '-' || sa.id
from duplicates d
where sa.id = d.id and d.rnum > 1;

-- Drop legacy partial index/constraint and create unconditional unique index for ON CONFLICT
alter table public.service_areas drop constraint if exists service_areas_slug_key;
drop index if exists public.idx_service_areas_slug;
drop index if exists public.idx_service_areas_slug_unique;
create unique index if not exists idx_service_areas_slug on public.service_areas (slug);

create index if not exists idx_service_areas_active
  on public.service_areas (is_active)
  where deleted_at is null;
create index if not exists idx_service_areas_sort_order
  on public.service_areas (sort_order)
  where deleted_at is null;

drop trigger if exists trigger_service_areas_touch_updated_at on public.service_areas;
create trigger trigger_service_areas_touch_updated_at
before update on public.service_areas
for each row
execute function public.touch_updated_at();

-- Seed all 10 Priority Target Service Areas
insert into public.service_areas (
  slug, name, summary, search_intent, highlights_text, meta_title, meta_description, sort_order, is_active
)
values
  (
    'jajpur-road',
    'Jajpur Road',
    'Flagship studio base and premier bridal academy salon. Instant appointment confirmations, bridal trials, and walk-in parlour services.',
    'Bridal makeup artist, beauty parlour, and makeup academy in Jajpur Road.',
    'Studio base & flagship academy\nWalk-in & bridal trials\nSame-day booking coordination',
    'Bridal Makeup Artist in Jajpur Road | Elegance Makeover',
    'Premier bridal makeup artist in Jajpur Road, Odisha. Master Artist Rasmirekha Swain offers luxury HD & Airbrush bridal makeover, parlour services & academy.',
    1,
    true
  ),
  (
    'vyasanagar',
    'Vyasanagar',
    'Direct municipal twin city to Jajpur Road. Fast venue dispatch for morning lagna rituals, reception styling, and party makeovers.',
    'Bridal makeup artist in Vyasanagar Odisha and beauty parlour services.',
    '5-10 min venue arrival\nMulti-person bridesmaid packages\nCustom Odia bridal drapes',
    'Bridal Makeup Artist in Vyasanagar | Elegance Makeover',
    'Top bridal makeup artist in Vyasanagar, Odisha. Master Artist Rasmirekha Swain delivers luxury HD & Airbrush wedding styling with 10-min venue arrival.',
    2,
    true
  ),
  (
    'jajpur-town',
    'Jajpur Town',
    'Heritage hub of the Biraja Temple. Full bridal entourage styling, mandap touchups, and sacred ritual longevity makeup.',
    'Bridal makeup artist in Jajpur Town near Biraja Temple.',
    'Biraja Kshetra wedding expertise\nHigh-humidity smudge resistance\nRitual-proof makeup',
    'Bridal Makeup Artist in Jajpur Town | Biraja Kshetra Makeovers',
    'Bespoke bridal makeover in Jajpur Town, Odisha by Rasmirekha Swain. Traditional Odia bridal styling, mukut fitting & 100% waterproof airbrush makeup.',
    3,
    true
  ),
  (
    'danagadi',
    'Danagadi',
    'Rapid on-venue service for industrial corridor wedding banquets, family ceremonies, and bridal party transformations.',
    'Bridal makeup artist in Danagadi and pre-wedding parlour services.',
    'Fast corridor travel\nComplete vanity mobile kit\nPre-bridal packages',
    'Bridal Makeup Artist in Danagadi | Elegance Makeover',
    'Luxury bridal makeup in Danagadi, Odisha. Professional artist travel for weddings, engagements & reception glam. Book Master Artist Rasmirekha Swain.',
    4,
    true
  ),
  (
    'kalinganagar',
    'Kalinganagar',
    'Corporate township weddings, guest house banquets, and high-glam evening receptions with premium HD airbrush styling.',
    'Bridal makeup in Kalinganagar Tata Steel township area.',
    'Township venue travel\nEvening reception glam\nHD longwear formulations',
    'Bridal Makeup Artist in Kalinganagar | Luxury Wedding Glam',
    'Premier bridal makeup in Kalinganagar, Odisha. On-venue luxury styling for Tata Steel township banquets, receptions & pre-bridal services by Rasmirekha.',
    5,
    true
  ),
  (
    'panikoili',
    'Panikoili',
    'Highway junction kalyan mandap weddings with punctual early morning travel and full bridal beauty kits.',
    'Bridal makeup artist in Panikoili Odisha near NH16.',
    'NH16 highway connectivity\nEarly morning call time\nAirbrush & HD packages',
    'Bridal Makeup Artist in Panikoili | Elegance Makeover',
    'Expert bridal makeup in Panikoili, Odisha near NH16. Punctual venue travel, high-durability HD airbrush cosmetics & saree draping for wedding muhurats.',
    6,
    true
  ),
  (
    'kuakhia',
    'Kuakhia',
    'South Jajpur wedding destinations, family celebrations, and traditional bride makeovers with bespoke jewellery setting.',
    'Bridal makeup artist in Kuakhia and wedding parlour services.',
    'Bespoke jewellery styling\nSaree draping specialists\nPre-wedding trial availability',
    'Bridal Makeup Artist in Kuakhia | Elegance Makeover',
    'Bespoke bridal makeup artist in Kuakhia, Odisha. Traditional Odia wedding makeover, jewellery placement & camera-ready finishes by Master Artist Rasmirekha.',
    7,
    true
  ),
  (
    'bhadrak',
    'Bhadrak',
    'Regular destination for brides and families traveling or booking Master Artist Rasmirekha Swain for high-end wedding artistry.',
    'Bridal makeup artist in Bhadrak and luxury wedding styling.',
    'Outstation bridal crew\n45-min transit connectivity\nMulti-event wedding booking',
    'Bridal Makeup Artist in Bhadrak | Luxury Wedding Makeover',
    'Top bridal makeup artist for Bhadrak weddings. Master Artist Rasmirekha Swain travels directly to your venue for luxury HD Airbrush bridal makeovers.',
    8,
    true
  ),
  (
    'cuttack',
    'Cuttack',
    'Silver City brides booking luxury HD airbrush makeup and aspiring students enrolling in professional makeup certification.',
    'Bridal makeup artist Cuttack and professional makeup academy.',
    'Grand heritage venue styling\nAcademy certification courses\nComprehensive bridal kits',
    'Bridal Makeup Artist in Cuttack | Luxury Wedding & Academy',
    'Luxury bridal makeup artist serving Cuttack, Odisha. High-definition airbrush bridal styling & certified makeup academy courses by Rasmirekha Swain.',
    9,
    true
  ),
  (
    'bhubaneswar',
    'Bhubaneswar',
    'Odisha capital destination weddings, luxury 5-star hotel receptions, and advanced masterclass students.',
    'Luxury bridal makeup artist Bhubaneswar and advanced makeup academy.',
    'Luxury hotel wedding artistry\n5-star banquet styling\nStatewide academy reputation',
    'Bridal Makeup Artist in Bhubaneswar | Luxury Wedding Artistry',
    'Celebrated bridal makeup artist serving Bhubaneswar destination weddings & 5-star receptions. Flawless 4K airbrush artistry by Rasmirekha Swain.',
    10,
    true
  )
on conflict (slug) do update set
  name = excluded.name,
  summary = excluded.summary,
  search_intent = excluded.search_intent,
  highlights_text = excluded.highlights_text,
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

-- ==============================================================================
-- 7. BLOG CATEGORIES, AUTHORS & 12 CORNERSTONE POSTS (E-E-A-T)
-- ==============================================================================

create table if not exists public.blog_categories (
  slug varchar(120) primary key,
  title varchar(160) not null,
  description text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_blog_categories_active
  on public.blog_categories (is_active)
  where deleted_at is null;
create index if not exists idx_blog_categories_sort_order
  on public.blog_categories (sort_order)
  where deleted_at is null;

drop trigger if exists trigger_blog_categories_touch_updated_at on public.blog_categories;
create trigger trigger_blog_categories_touch_updated_at
before update on public.blog_categories
for each row
execute function public.touch_updated_at();

insert into public.blog_categories (slug, title, description, sort_order, is_active)
values
  ('bridal', 'Bridal', 'Bridal makeup guidance and wedding day preparation.', 1, true),
  ('academy', 'Academy', 'Beauty education, training and certification insights.', 2, true),
  ('skincare', 'Skincare', 'Pre-bridal and event skincare routines.', 3, true),
  ('beauty-tips', 'Beauty Tips', 'Practical everyday beauty and glam tips.', 4, true)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  updated_at = now();

create table if not exists public.blog_authors (
  slug varchar(120) primary key,
  name varchar(160) not null,
  bio text,
  avatar_url varchar(255),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_blog_authors_active
  on public.blog_authors (is_active)
  where deleted_at is null;

drop trigger if exists trigger_blog_authors_touch_updated_at on public.blog_authors;
create trigger trigger_blog_authors_touch_updated_at
before update on public.blog_authors
for each row
execute function public.touch_updated_at();

insert into public.blog_authors (slug, name, bio, avatar_url, is_active)
values
  (
    'rasmirekha-swain',
    'Rasmirekha Swain',
    'Founder of Elegance Makeover & Academy and lead bridal artist in Jajpur Road, Odisha. Over 10+ years transforming brides with HD, Airbrush and traditional Odia bridal artistry.',
    '/assets/owner.webp',
    true
  )
on conflict (slug) do update set
  name = excluded.name,
  bio = excluded.bio,
  avatar_url = excluded.avatar_url,
  updated_at = now();

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug varchar(180) not null unique,
  title varchar(255) not null,
  excerpt text not null,
  content_text text not null,
  featured_image_url varchar(255),
  tags_text text,
  category_slug varchar(120) not null references public.blog_categories(slug) on update cascade on delete restrict,
  author_slug varchar(120) not null references public.blog_authors(slug) on update cascade on delete restrict,
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_reviewed_at timestamptz default now(),
  reviewer_slug text default 'rasmirekha-swain',
  seo_title varchar(255),
  seo_description text,
  faq_json jsonb default '[]'::jsonb,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.blog_posts
  add column if not exists last_reviewed_at timestamptz default now(),
  add column if not exists reviewer_slug text default 'rasmirekha-swain',
  add column if not exists faq_json jsonb default '[]'::jsonb;

-- Ensure slug is unconditionally uniquely indexed for ON CONFLICT
alter table public.blog_posts drop constraint if exists blog_posts_slug_key;
drop index if exists public.idx_blog_posts_slug;
create unique index if not exists idx_blog_posts_slug on public.blog_posts (slug);

create index if not exists idx_blog_posts_published
  on public.blog_posts (is_published, published_at desc)
  where deleted_at is null;
create index if not exists idx_blog_posts_category
  on public.blog_posts (category_slug)
  where deleted_at is null;
create index if not exists idx_blog_posts_author
  on public.blog_posts (author_slug)
  where deleted_at is null;
create index if not exists idx_blog_posts_featured
  on public.blog_posts (is_featured)
  where deleted_at is null;

drop trigger if exists trigger_blog_posts_touch_updated_at on public.blog_posts;
create trigger trigger_blog_posts_touch_updated_at
before update on public.blog_posts
for each row
execute function public.touch_updated_at();

-- Seed 12 Cornerstone Blog Posts
insert into public.blog_posts (
  slug, title, excerpt, content_text, featured_image_url, tags_text,
  category_slug, author_slug, published_at, updated_at, last_reviewed_at,
  seo_title, seo_description, is_featured, is_published, sort_order
)
values
  (
    'bridal-makeup-cost-odisha',
    'Bridal Makeup Cost in Odisha: Complete 2026 Price Guide',
    'Comprehensive breakdown of bridal makeup pricing across Odisha, from Classic HD at ₹8,000 to Luxury Airbrush at ₹16,000, including artist travel policies.',
    $$Planning wedding expenses in Odisha requires transparency. In 2026, professional bridal makeup packages typically range from ₹6,000 to ₹18,000, determined by formulation (HD vs Airbrush), artist seniority, and venue travel distance. Signature HD bridal makeup is ₹8,000 - ₹12,000, while Airbrush packages range from ₹12,000 to ₹16,000, including luxury skin prep, 3D lashes, hair styling, Odia saree draping, and mukut placement.$$,
    'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    'bridal makeup cost Odisha,bridal makeup price Jajpur Road,HD bridal makeup rate Cuttack,airbrush bridal makeup cost Bhubaneswar',
    'bridal',
    'rasmirekha-swain',
    '2026-06-01T00:00:00Z',
    now(),
    now(),
    'Bridal Makeup Cost in Odisha | 2026 Price Guide',
    'Discover exact bridal makeup costs in Odisha. Compare HD vs Airbrush rates in Jajpur Road, Cuttack & Bhubaneswar with inclusions breakdown.',
    true,
    true,
    1
  ),
  (
    'odia-bridal-makeup-guide',
    'Odia Bridal Makeup Look: Traditions, Mukut & Saree Draping',
    'Everything you need to know about crafting an authentic Odia bridal makeover, from intricate chandan designs to royal mukut balancing.',
    $$The quintessential Odia bride embodies divine grace, tradition, and regal simplicity. Central to the Odia bridal aesthetic is the Mukut crown and delicate Chandan art framing the forehead. At Elegance Makeover, smudge-resistant waterproof liquid pigments ensure motifs remain crisp through ceremonial smoke and humidity.$$,
    'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80',
    'Odia bridal makeup,traditional Odia bride,mukut fitting Odia wedding,Odia bridal saree drape,chandan art bride',
    'bridal',
    'rasmirekha-swain',
    '2026-06-05T00:00:00Z',
    now(),
    now(),
    'Odia Bridal Makeup Look: Traditional Styling Guide',
    'Complete guide to the traditional Odia bridal look. Master mukut fitting, chandan bindi art, red sambalpuri saree draping & sweatproof bridal bases.',
    true,
    true,
    2
  ),
  (
    'hd-vs-airbrush-makeup-indian-skin',
    'HD vs Airbrush Makeup for Indian Skin Tones & Humid Climates',
    'Detailed technical comparison between High-Definition brushwork and Airbrush micro-spraying to help you choose the right base for your wedding day.',
    $$HD makeup uses micronized liquid foundations applied with dense buffing brushes for custom blendability and radiance (lasting 12-14 hours). Airbrush makeup mists microscopic silicone droplets through a precision compressor, creating a 100% waterproof, tear-resistant shield ideal for coastal Odisha humidity and 4K cameras.$$,
    'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&q=80',
    'HD vs airbrush makeup,airbrush makeup Indian skin,bridal makeup humidity Odisha,waterproof wedding makeup',
    'bridal',
    'rasmirekha-swain',
    '2026-06-10T00:00:00Z',
    now(),
    now(),
    'HD vs Airbrush Makeup for Indian Skin | Comparison',
    'Compare HD vs Airbrush makeup for Indian skin. Discover longevity, waterproof performance, camera finish, and pricing differences in Odisha.',
    true,
    true,
    3
  ),
  (
    'pre-bridal-skincare-timeline',
    'Pre-Bridal Skincare Timeline: 6-Month Countdown to Radiant Glow',
    'Achieve radiant glass skin on your wedding day with this expert month-by-month skincare and aesthetic treatment schedule.',
    $$Flawless wedding-day makeup begins months before foundation. At 6 months: consult an expert, establish AHA/BHA, vitamin C and SPF routines. At 3 months: schedule monthly Hydra Facials for vortex extraction. At 1 week: focus strictly on barrier hydration, sleep, and avoid new chemical experiments.$$,
    'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    'pre bridal skincare,wedding skincare timeline,hydra facial bride,pre bridal packages Jajpur Road',
    'skincare',
    'rasmirekha-swain',
    '2026-06-15T00:00:00Z',
    now(),
    now(),
    'Pre-Bridal Skincare Timeline | 6-Month Wedding Routine',
    'Step-by-step pre-bridal skincare schedule from 6 months to 1 week before wedding day. Facials, hydra-dermabrasion, diet tips & chemical peel warnings.',
    false,
    true,
    4
  ),
  (
    'makeup-artist-course-fees-career-odisha',
    'Makeup Artist Course Fees & Career Opportunities in Odisha',
    'Complete guide to enrolling in a certified professional makeup academy in Odisha, with realistic career pathways, tool kit investments, and earning potential.',
    $$Bridal beauty in Odisha is booming. Foundational 1-month certificates range from ₹15,000 to ₹20,000, while comprehensive 3-month Professional Bridal & Airbrush Diplomas range from ₹35,000 to ₹50,000. At Elegance Academy, students receive 100% hands-on training on live models covering base science, airbrushing, and client pricing.$$,
    'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=800&q=80',
    'makeup artist course fees Odisha,makeup academy Jajpur Road,beautician course Cuttack,bridal makeup training Bhubaneswar',
    'academy',
    'rasmirekha-swain',
    '2026-06-20T00:00:00Z',
    now(),
    now(),
    'Makeup Artist Course Fees & Career Guide in Odisha',
    'Explore professional makeup artist courses in Odisha. Learn course fees, duration, hands-on model syllabus, certification & career earnings in 2026.',
    true,
    true,
    5
  ),
  (
    'wedding-day-makeup-checklist',
    'The Ultimate Wedding-Day Makeup & Bridal Touch-Up Checklist',
    'Never forget an essential detail with this comprehensive wedding morning checklist designed specifically for Indian and Odia brides.',
    $$Morning Logistics: Start hair and makeup 4 hours prior to the Baraat arrival in a button-down shirt. Emergency Vanity Kit: pack blotting papers, sample lip color, lash glue, bobby pins, and safety pins. During mandap rituals, dab tears gently below the waterline—never wipe across the cheek.$$,
    'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    'wedding day makeup checklist,bridal emergency kit,bridal touchup tips,wedding day timeline bride',
    'bridal',
    'rasmirekha-swain',
    '2026-06-25T00:00:00Z',
    now(),
    now(),
    'Wedding-Day Makeup Checklist: Bride''s Survival Guide',
    'Essential wedding-day bridal beauty checklist for Indian brides. Timeline planning, vanity emergency kit items, and touch-up tips for the mandap.',
    false,
    true,
    6
  ),
  (
    'hairstyles-for-odia-weddings',
    'Traditional & Modern Hairstyles for Odia Weddings: Gajra & Mukut',
    'From classical low donut buns adorned with fresh mogra strings to modern cascading Hollywood waves, explore the finest bridal hair designs.',
    $$Bridal hair architecture for Odia weddings requires structural integrity to support the heavy mukut, matha patti, and veil. Classic low buns with fragrant Mogra gajra are favored for lagna, while textured floral chignons and modern waves star in evening receptions.$$,
    'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
    'Odia wedding hairstyles,bridal gajra hairstyles,bridal bun with mukut,Odia bride hairstyle Jajpur',
    'beauty-tips',
    'rasmirekha-swain',
    '2026-07-01T00:00:00Z',
    now(),
    now(),
    'Hairstyles for Odia Weddings: Gajra, Buns & Mukut',
    'Explore 8 gorgeous hairstyles for Odia brides. Discover how to style fresh jasmine gajra, anchor heavy mukuts, and create textured messy buns.',
    false,
    true,
    7
  ),
  (
    'bridal-makeup-for-all-skin-tones',
    'Bridal Makeup Guide for Oily, Dry & Dusky Indian Skin Tones',
    'How to avoid ashy bases and flash-back by matching warm golden undertones and tailoring prep for oily vs dry skin textures.',
    $$Ashy bases occur when foundation is too light or has cool pink undertones on warm golden or olive Indian skin. Custom peach and yellow color-correction balances undertones seamlessly with the collarbone. Oily skin benefits from target baking; dry complexions require deep hyaluronic moisture prep.$$,
    'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
    'bridal makeup dusky Indian skin,bridal makeup oily skin Odisha,undertone matching Indian bride,warm undertone makeup',
    'bridal',
    'rasmirekha-swain',
    '2026-07-05T00:00:00Z',
    now(),
    now(),
    'Bridal Makeup for Indian Skin Tones & Skin Types',
    'Expert undertone matching, baking techniques & foundation formulations for dusky, warm, oily, and dry Indian skin tones. Read pro tips.',
    false,
    true,
    8
  ),
  (
    'haldi-mehendi-makeup-looks',
    'Haldi & Mehendi Makeup: Waterproof Glow & Floral Aesthetics',
    'Keep your pre-wedding function looks fresh, playful, and stain-resistant with these expert Haldi and Mehendi beauty tips.',
    $$Haldi ceremonies require minimal, stain-resistant makeup. Lightweight tinted moisturizers, waterproof eyebrow pomades, and water-repellent setting sprays ensure the base survives turmeric paste and playful rituals. Mehendi nights call for glowing glass skin and boho braids with fresh floral jewels.$$,
    'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80',
    'Haldi makeup look,Mehendi bridal look,waterproof Haldi makeup,floral jewelry styling bride',
    'bridal',
    'rasmirekha-swain',
    '2026-07-10T00:00:00Z',
    now(),
    now(),
    'Haldi & Mehendi Makeup Looks: Glow & Waterproof Guide',
    'Trending Haldi and Mehendi makeover ideas. Waterproof sweat-resistant yellow-proof base, floral hair accessories, and glass skin looks.',
    false,
    true,
    9
  ),
  (
    'how-to-choose-bridal-makeup-artist-odisha',
    'How to Choose the Best Bridal Makeup Artist in Odisha: 7 Vital Factors',
    'Avoid wedding morning disasters by screening potential bridal artists across portfolio authenticity, cosmetic brands, and contract terms.',
    $$Selecting the right bridal makeup artist is critical: 1) Verify real high-resolution client videos showing natural skin texture, 2) Inquire about genuine luxury brands (Dior, MAC, Huda Beauty), 3) Confirm sanitation of brushes and disposable wands, and 4) Ensure regional experience with Odia mukuts and lagna timelines.$$,
    'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    'best makeup artist Odisha,how to choose bridal makeup artist,bridal makeup artist Jajpur Road,bridal makeup artist Cuttack',
    'beauty-tips',
    'rasmirekha-swain',
    '2026-07-15T00:00:00Z',
    now(),
    now(),
    'How to Choose Bridal Makeup Artist in Odisha | 7 Tips',
    '7 essential criteria for picking your bridal makeup artist in Odisha. Review portfolios, check genuine testimonials, verify hygiene & understand contracts.',
    false,
    true,
    10
  ),
  (
    'airbrush-bridal-makeup-step-by-step',
    'Step-by-Step Airbrush Bridal Makeup: What Happens on Your Wedding Morning',
    'A behind-the-chair look at how Master Artist Rasmirekha Swain transforms brides with micro-fine silicone airbrush compressors.',
    $$A full airbrush session follows 4 precise stages: 1) Dermal clarification and silicone barrier priming (0-25m), 2) Precision eye artistry and brow architecture prior to base work (25-65m), 3) Micro-mist compressor foundation dispersion (65-95m), and 4) Hair architecture, mukut anchoring, and saree pleating (95-180m).$$,
    'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&q=80',
    'airbrush makeup process,airbrush wedding makeup steps,airbrush compressor makeup,airbrush bridal Jajpur Road',
    'bridal',
    'rasmirekha-swain',
    '2026-07-20T00:00:00Z',
    now(),
    now(),
    'Step-by-Step Airbrush Bridal Makeup: The Experience',
    'Detailed walk-through of an HD Airbrush bridal makeup session. Discover compressor setup, silicone dispersion, eyebrow mapping, and setting.',
    false,
    true,
    11
  ),
  (
    'post-bridal-skincare-makeup-removal',
    'Post-Bridal Skincare: Safe Heavy Makeup Removal & Skin Recovery',
    'Protect your skin barrier after days of heavy wedding makeup and sacred ritual smoke with this gentle recovery protocol.',
    $$Never sleep in heavy bridal makeup. Double-cleansing is vital: 1) Soak lash glue with oil micellar water to slip lashes off gently, 2) Massage a rich cleansing balm onto dry skin for 60s to break down silicone airbrush polymers, 3) Rinse with a sulfate-free foaming cleanser, and 4) Restore skin barrier with ceramide and hyaluronic serums.$$,
    'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    'how to remove bridal makeup,remove airbrush makeup,post bridal skincare,double cleansing bride',
    'skincare',
    'rasmirekha-swain',
    '2026-07-25T00:00:00Z',
    now(),
    now(),
    'Post-Bridal Skincare: Safe Makeup Removal & Recovery',
    'How to safely remove waterproof bridal and airbrush makeup without irritation. Double-cleansing methods, barrier recovery & soothing serums.',
    false,
    true,
    12
  )
on conflict (slug) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  content_text = excluded.content_text,
  featured_image_url = excluded.featured_image_url,
  tags_text = excluded.tags_text,
  category_slug = excluded.category_slug,
  author_slug = excluded.author_slug,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  is_featured = excluded.is_featured,
  is_published = excluded.is_published,
  sort_order = excluded.sort_order,
  last_reviewed_at = now(),
  updated_at = now();

-- Seed Sample Pricing Packages
insert into public.pricing_packages (name, price, popular, features_text, sort_order, is_active)
values
  (
    'Classic Bride',
    6000,
    false,
    'Signature bridal makeup\nPolished hair styling\n3-hour appointment window\nBasic touch-up support\nOne attendant consultation',
    1,
    true
  ),
  (
    'Royal Bride',
    8000,
    true,
    'Premium bridal makeup\nLuxury hair design and draping\n4-hour appointment window\n2 complimentary touch-ups\nBride''s mother makeup included\nTrial session included',
    2,
    true
  ),
  (
    'Maharani Bride',
    12000,
    false,
    'Haute couture bridal makeup\nEditorial hair styling\n4+ hour appointment window\nUnlimited touch-up support\nFamily member makeup\nDress consultation\nPre-wedding shoot coordination',
    3,
    true
  )
on conflict (name) do update set
  price = excluded.price,
  popular = excluded.popular,
  features_text = excluded.features_text,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

create index if not exists idx_hero_content_active
  on public.hero_content (is_active);
create index if not exists idx_about_content_active
  on public.about_content (is_active);
create index if not exists idx_contact_settings_active
  on public.contact_settings (is_active);
create index if not exists idx_social_links_active
  on public.social_links (is_active);
create index if not exists idx_seo_settings_active
  on public.seo_settings (is_active);

-- ==============================================================================
-- 8. ANALYTICAL VIEWS
-- ==============================================================================

create or replace view public.upcoming_bookings as
select
  b.id,
  b.booking_code,
  b.customer_name,
  b.phone,
  b.email,
  b.service_name,
  b.booking_date,
  b.booking_time,
  b.duration_minutes,
  b.status,
  b.source,
  cp.preferred_contact_method,
  s.duration_label,
  s.category
from public.bookings b
left join public.customer_preferences cp on b.phone = cp.customer_phone
left join public.services s on b.service_id = s.id
where b.deleted_at is null
  and b.booking_date >= current_date
  and b.status not in ('rejected', 'cancelled')
order by b.booking_date, b.booking_time;

create or replace view public.booking_stats as
select 'Total Bookings' as metric, count(*) as value
from public.bookings
where deleted_at is null
union all
select 'Approved Bookings', count(*)
from public.bookings
where deleted_at is null and status = 'approved'
union all
select 'Pending Bookings', count(*)
from public.bookings
where deleted_at is null and status = 'pending'
union all
select 'Unique Customers', count(distinct phone)
from public.bookings
where deleted_at is null
union all
select 'Total Revenue', coalesce(sum(amount_paid), 0)::bigint
from public.bookings
where deleted_at is null and status = 'completed';

create or replace view public.service_popularity as
select
  s.id,
  s.title,
  s.category,
  count(b.id) as booking_count,
  count(b.id) * 100.0 / nullif(sum(count(b.id)) over (), 0) as percentage,
  coalesce(sum(b.amount_paid), 0) as revenue_generated
from public.services s
left join public.bookings b
  on s.id = b.service_id and b.deleted_at is null
where s.deleted_at is null
group by s.id, s.title, s.category
order by booking_count desc;

create or replace view public.customer_engagement as
select
  cp.customer_phone,
  cp.customer_email,
  cp.customer_name,
  cp.total_bookings,
  cp.total_spent,
  cp.loyalty_points,
  cp.last_booking_date,
  case
    when cp.total_bookings >= 5 then 'VIP'
    when cp.total_bookings >= 3 then 'Regular'
    else 'New'
  end as customer_tier,
  case
    when cp.last_booking_date < current_date - interval '90 days' then 'Inactive'
    when cp.last_booking_date < current_date - interval '30 days' then 'At Risk'
    else 'Active'
  end as engagement_status
from public.customer_preferences cp
order by cp.total_spent desc;

create or replace view public.recent_activity as
select
  'booking' as activity_type,
  b.booking_code as entity_id,
  b.customer_name as description,
  b.status as status,
  b.updated_at as activity_date
from public.bookings b
where b.deleted_at is null
union all
select
  'testimonial',
  t.id::text,
  concat(t.customer_name, ' - ', t.service_name),
  t.status,
  t.updated_at
from public.testimonials t
where t.deleted_at is null
union all
select
  'offer',
  o.id::text,
  o.title,
  o.status,
  o.updated_at
from public.offers o
where o.deleted_at is null
order by activity_date desc
limit 50;

create or replace view public.notification_queue_status as
select
  notification_type,
  channel,
  status,
  count(*) as count,
  count(*) filter (where created_at > now() - interval '24 hours') as last_24h
from public.notifications
group by notification_type, channel, status
order by notification_type, channel;

create or replace view public.revenue_summary as
select
  b.booking_date,
  count(*) as booking_count,
  coalesce(sum(b.amount_quoted), 0) as quoted_amount,
  coalesce(sum(b.amount_paid), 0) as received_amount,
  coalesce(sum(coalesce(b.amount_quoted, 0) - coalesce(b.amount_paid, 0)), 0) as pending_amount,
  count(*) filter (where b.payment_status = 'paid') as paid_count,
  count(*) filter (where b.payment_status = 'unpaid') as unpaid_count
from public.bookings b
where b.deleted_at is null and b.status = 'completed'
group by b.booking_date
order by b.booking_date desc;

-- ==============================================================================
-- 9. FUNCTIONS & BUSINESS TRIGGERS
-- ==============================================================================

create or replace function public.generate_booking_code()
returns varchar
language plpgsql
as $$
declare
  new_code varchar;
  attempt_count int := 0;
begin
  loop
    new_code := 'EM-' || to_char(current_date, 'YYMMDD') || '-' || lpad((floor(random() * 9000) + 1000)::text, 4, '0');
    if not exists (select 1 from public.bookings where booking_code = new_code) then
      return new_code;
    end if;

    attempt_count := attempt_count + 1;
    if attempt_count > 1000 then
      raise exception 'Could not generate unique booking code';
    end if;
  end loop;
end;
$$;

create or replace function public.update_customer_preferences()
returns trigger
language plpgsql
as $$
begin
  if new.deleted_at is null and new.status = 'completed' then
    if tg_op = 'INSERT' or old.status is distinct from new.status then
      insert into public.customer_preferences (
        customer_phone,
        customer_email,
        customer_name,
        total_bookings,
        total_spent,
        last_booking_date
      ) values (
        new.phone,
        new.email,
        new.customer_name,
        1,
        coalesce(new.amount_paid, 0),
        new.booking_date
      )
      on conflict (customer_phone) do update set
        customer_email = coalesce(excluded.customer_email, public.customer_preferences.customer_email),
        customer_name = excluded.customer_name,
        total_bookings = public.customer_preferences.total_bookings + 1,
        total_spent = public.customer_preferences.total_spent + coalesce(excluded.total_spent, 0),
        last_booking_date = excluded.last_booking_date,
        updated_at = now();
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trigger_update_customer_preferences on public.bookings;
create trigger trigger_update_customer_preferences
after insert or update of status on public.bookings
for each row
execute function public.update_customer_preferences();

create or replace function public.trigger_notifications_on_booking_update()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'UPDATE' and old.status is distinct from new.status then
    insert into public.notifications (
      booking_id,
      customer_email,
      customer_phone,
      notification_type,
      template_name,
      channel,
      status
    ) values (
      new.id,
      new.email,
      new.phone,
      'status_update',
      'booking_status_changed',
      'email',
      'pending'
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trigger_booking_notifications on public.bookings;
create trigger trigger_booking_notifications
after update on public.bookings
for each row
execute function public.trigger_notifications_on_booking_update();

-- ==============================================================================
-- 10. ROW LEVEL SECURITY (RLS) & PUBLIC ACCESS POLICIES
-- ==============================================================================

create or replace function public.current_admin_user_id()
returns uuid
language sql
stable
as $$
  select au.id
  from public.admin_users au
  where au.auth_user_id = auth.uid()
    and au.is_active = true
  limit 1
$$;

create or replace function public.current_admin_role()
returns text
language sql
stable
as $$
  select coalesce((
    select au.role
    from public.admin_users au
    where au.auth_user_id = auth.uid()
      and au.is_active = true
    limit 1
  ), '')
$$;

create or replace function public.is_authenticated_admin()
returns boolean
language sql
stable
as $$
  select public.current_admin_user_id() is not null
$$;

-- Enable RLS across all tables
alter table public.admin_users enable row level security;
alter table public.audit_logs enable row level security;
alter table public.rate_limits enable row level security;
alter table public.services enable row level security;
alter table public.service_areas enable row level security;
alter table public.blog_categories enable row level security;
alter table public.blog_authors enable row level security;
alter table public.blog_posts enable row level security;
alter table public.gallery enable row level security;
alter table public.testimonials enable row level security;
alter table public.offers enable row level security;
alter table public.advertisements enable row level security;
alter table public.bookings enable row level security;
alter table public.contact_messages enable row level security;
alter table public.hero_content enable row level security;
alter table public.about_content enable row level security;
alter table public.contact_settings enable row level security;
alter table public.social_links enable row level security;
alter table public.seo_settings enable row level security;
alter table public.pricing_packages enable row level security;
alter table public.faq_sections enable row level security;

-- Admin access policies
drop policy if exists "admin users read by admins" on public.admin_users;
create policy "admin users read by admins"
on public.admin_users for select
using (public.is_authenticated_admin());

drop policy if exists "admin users manage by super admin" on public.admin_users;
create policy "admin users manage by super admin"
on public.admin_users for all
using (public.current_admin_role() = 'super_admin')
with check (public.current_admin_role() = 'super_admin');

drop policy if exists "audit logs read by admins" on public.audit_logs;
create policy "audit logs read by admins"
on public.audit_logs for select
using (public.is_authenticated_admin());

drop policy if exists "audit logs insert by admins" on public.audit_logs;
create policy "audit logs insert by admins"
on public.audit_logs for insert
with check (public.is_authenticated_admin());

drop policy if exists "rate limits by admins" on public.rate_limits;
create policy "rate limits by admins"
on public.rate_limits for all
using (public.is_authenticated_admin())
with check (public.is_authenticated_admin());

-- Grants for Supabase API access
grant usage on schema public to anon, authenticated, service_role;
grant select on public.services to anon, authenticated;
grant select on public.service_areas to anon, authenticated;
grant select on public.blog_categories to anon, authenticated;
grant select on public.blog_authors to anon, authenticated;
grant select on public.blog_posts to anon, authenticated;
grant select on public.gallery to anon, authenticated;
grant select on public.testimonials to anon, authenticated;
grant select on public.offers to anon, authenticated;
grant select on public.pricing_packages to anon, authenticated;
grant select on public.faq_sections to anon, authenticated;
grant select on public.hero_content to anon, authenticated;
grant select on public.about_content to anon, authenticated;
grant select on public.contact_settings to anon, authenticated;
grant select on public.social_links to anon, authenticated;
grant select on public.seo_settings to anon, authenticated;

grant insert on public.bookings to anon, authenticated;
grant insert on public.contact_messages to anon, authenticated;

grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
grant all on all routines in schema public to service_role;

-- Public Read Policies (idempotent creation)
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'services' and policyname = 'Public can view active services') then
    create policy "Public can view active services" on public.services for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'service_areas' and policyname = 'Public can view active service areas') then
    create policy "Public can view active service areas" on public.service_areas for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'blog_categories' and policyname = 'Public can view active blog categories') then
    create policy "Public can view active blog categories" on public.blog_categories for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'blog_authors' and policyname = 'Public can view active blog authors') then
    create policy "Public can view active blog authors" on public.blog_authors for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'blog_posts' and policyname = 'Public can view published blog posts') then
    create policy "Public can view published blog posts" on public.blog_posts for select using (is_published = true and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'gallery' and policyname = 'Public can view active gallery items') then
    create policy "Public can view active gallery items" on public.gallery for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'testimonials' and policyname = 'Public can view visible testimonials') then
    create policy "Public can view visible testimonials" on public.testimonials for select using (status = 'visible' and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'offers' and policyname = 'Public can view active offers') then
    create policy "Public can view active offers" on public.offers for select using (status = 'active' and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'pricing_packages' and policyname = 'Public can view active pricing packages') then
    create policy "Public can view active pricing packages" on public.pricing_packages for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'faq_sections' and policyname = 'Public can view active faq sections') then
    create policy "Public can view active faq sections" on public.faq_sections for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'hero_content' and policyname = 'Public can view active hero content') then
    create policy "Public can view active hero content" on public.hero_content for select using (is_active = true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'about_content' and policyname = 'Public can view active about content') then
    create policy "Public can view active about content" on public.about_content for select using (is_active = true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'contact_settings' and policyname = 'Public can view active contact settings') then
    create policy "Public can view active contact settings" on public.contact_settings for select using (is_active = true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'social_links' and policyname = 'Public can view active social links') then
    create policy "Public can view active social links" on public.social_links for select using (is_active = true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'seo_settings' and policyname = 'Public can view active seo settings') then
    create policy "Public can view active seo settings" on public.seo_settings for select using (is_active = true);
  end if;
end;
$$;
