-- ============================================
-- ELEGANCE SPARKLE LUXE - SUPABASE SCHEMA
-- Aligned with the current codebase
-- ============================================

-- Helpful utility for updated_at maintenance
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create extension if not exists pgcrypto;

-- ============================================
-- CORE TABLES
-- ============================================

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(191) not null unique,
  password_hash varchar(255) default '',
  role text not null default 'admin' check (role in ('admin', 'manager', 'staff')),
  last_login timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.users
  alter column password_hash drop not null;
alter table public.users
  alter column password_hash set default '';

create unique index if not exists idx_users_email
  on public.users (email)
  where deleted_at is null;

drop trigger if exists trigger_users_touch_updated_at on public.users;
create trigger trigger_users_touch_updated_at
before update on public.users
for each row
execute function public.touch_updated_at();

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  email text not null unique,
  role text not null default 'editor' check (role in ('super_admin', 'admin', 'editor')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_admin_users_auth_user_id
  on public.admin_users (auth_user_id);
create index if not exists idx_admin_users_role
  on public.admin_users (role);
create index if not exists idx_admin_users_active
  on public.admin_users (is_active);

drop trigger if exists trigger_admin_users_touch_updated_at on public.admin_users;
create trigger trigger_admin_users_touch_updated_at
before update on public.admin_users
for each row
execute function public.touch_updated_at();

insert into public.admin_users (auth_user_id, email, role, is_active, created_at, updated_at)
values
  (null, 'elegancemakeover.2021@gmail.com', 'super_admin', true, now(), now())
on conflict (email) do update set
  role = excluded.role,
  is_active = true,
  updated_at = now();

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  category text not null check (category in ('bridal', 'parlour', 'academy')),
  description text not null,
  price_label varchar(64) not null,
  price_min numeric(10,2),
  price_max numeric(10,2),
  duration_label varchar(64) not null,
  duration_minutes int,
  featured boolean not null default false,
  image_url varchar(255),
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_services_category
  on public.services (category)
  where deleted_at is null;
create index if not exists idx_services_active
  on public.services (is_active)
  where deleted_at is null;
create index if not exists idx_services_sort_order
  on public.services (sort_order);

drop trigger if exists trigger_services_touch_updated_at on public.services;
create trigger trigger_services_touch_updated_at
before update on public.services
for each row
execute function public.touch_updated_at();

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  category text not null check (category in ('bridal', 'parlour', 'before_after', 'academy')),
  image_url varchar(255) not null,
  alt_text varchar(255) not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_gallery_category
  on public.gallery (category)
  where deleted_at is null;
create index if not exists idx_gallery_active
  on public.gallery (is_active)
  where deleted_at is null;
create index if not exists idx_gallery_sort_order
  on public.gallery (sort_order);

drop trigger if exists trigger_gallery_touch_updated_at on public.gallery;
create trigger trigger_gallery_touch_updated_at
before update on public.gallery
for each row
execute function public.touch_updated_at();

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  customer_name varchar(120) not null,
  customer_email varchar(191),
  service_name varchar(160) not null,
  rating smallint not null check (rating between 1 and 5),
  review_text text not null,
  status text not null default 'visible' check (status in ('visible', 'draft', 'archived')),
  booking_id bigint,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_testimonials_status
  on public.testimonials (status)
  where deleted_at is null;
create index if not exists idx_testimonials_rating
  on public.testimonials (rating)
  where deleted_at is null;

drop trigger if exists trigger_testimonials_touch_updated_at on public.testimonials;
create trigger trigger_testimonials_touch_updated_at
before update on public.testimonials
for each row
execute function public.touch_updated_at();

create table if not exists public.offers (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  discount_label varchar(64) not null,
  discount_percentage smallint check (discount_percentage between 0 and 100),
  description text not null,
  valid_from date not null,
  valid_until date not null,
  status text not null default 'scheduled' check (status in ('scheduled', 'active', 'expired', 'paused')),
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_offers_status_dates
  on public.offers (status, valid_from, valid_until)
  where deleted_at is null;

drop trigger if exists trigger_offers_touch_updated_at on public.offers;
create trigger trigger_offers_touch_updated_at
before update on public.offers
for each row
execute function public.touch_updated_at();

create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  asset_url varchar(255) not null,
  asset_type text not null default 'poster' check (asset_type in ('poster', 'banner', 'carousel', 'story')),
  platform text default 'website' check (platform in ('website', 'instagram', 'facebook', 'whatsapp')),
  start_date date not null,
  end_date date not null,
  status text not null default 'active' check (status in ('active', 'paused', 'archived', 'scheduled')),
  impressions int not null default 0,
  clicks int not null default 0,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_advertisements_status_dates
  on public.advertisements (status, start_date, end_date)
  where deleted_at is null;

drop trigger if exists trigger_advertisements_touch_updated_at on public.advertisements;
create trigger trigger_advertisements_touch_updated_at
before update on public.advertisements
for each row
execute function public.touch_updated_at();

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_code varchar(32) not null unique,
  customer_name varchar(120) not null,
  phone varchar(32) not null,
  email varchar(191),
  service_id bigint references public.services(id) on delete set null,
  service_name varchar(160) not null,
  booking_date date not null,
  booking_time varchar(32) not null,
  duration_minutes int,
  notes text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'rescheduled', 'completed', 'cancelled')),
  source text not null default 'website' check (source in ('website', 'whatsapp', 'call', 'walk_in', 'instagram')),
  amount_quoted numeric(10,2),
  amount_paid numeric(10,2),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'partial', 'paid', 'refunded')),
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_bookings_date_status
  on public.bookings (booking_date, status)
  where deleted_at is null;
create index if not exists idx_bookings_customer_phone
  on public.bookings (phone)
  where deleted_at is null;
create index if not exists idx_bookings_email
  on public.bookings (email)
  where deleted_at is null;
create index if not exists idx_bookings_code
  on public.bookings (booking_code)
  where deleted_at is null;
create index if not exists idx_bookings_created_at
  on public.bookings (created_at desc)
  where deleted_at is null;

drop trigger if exists trigger_bookings_touch_updated_at on public.bookings;
create trigger trigger_bookings_touch_updated_at
before update on public.bookings
for each row
execute function public.touch_updated_at();

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  phone varchar(32) not null,
  email varchar(191),
  service_name varchar(160),
  message text not null,
  status text not null default 'new' check (status in ('new', 'read', 'replied', 'archived')),
  response_notes text,
  replied_at timestamptz,
  replied_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_contact_messages_status
  on public.contact_messages (status)
  where deleted_at is null;
create index if not exists idx_contact_messages_email
  on public.contact_messages (email)
  where deleted_at is null;

drop trigger if exists trigger_contact_messages_touch_updated_at on public.contact_messages;
create trigger trigger_contact_messages_touch_updated_at
before update on public.contact_messages
for each row
execute function public.touch_updated_at();

create table if not exists public.rate_limits (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  endpoint text not null,
  count int not null default 1,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_rate_limits_ip_endpoint
  on public.rate_limits (ip_hash, endpoint);
create index if not exists idx_rate_limits_expires_at
  on public.rate_limits (expires_at);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid,
  action varchar(50) not null,
  resource_type varchar(80) not null,
  resource_id text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.audit_logs
  add column if not exists created_at timestamptz default now();
alter table public.audit_logs
  drop constraint if exists audit_logs_user_id_fkey;
alter table public.audit_logs
  add column if not exists resource_type varchar(80);
alter table public.audit_logs
  add column if not exists resource_id text default '';
alter table public.audit_logs
  add column if not exists metadata jsonb default '{}'::jsonb;
alter table public.audit_logs
  alter column metadata set default '{}'::jsonb;
alter table public.audit_logs
  alter column resource_id set default '';
alter table public.audit_logs
  alter column resource_type set default 'unknown';

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'audit_logs'
      and column_name = 'timestamp'
  ) then
    execute $sql$
      update public.audit_logs
      set created_at = coalesce(created_at, timestamp)
      where created_at is null
    $sql$;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'audit_logs'
      and column_name = 'table_name'
  ) then
    execute $sql$
      update public.audit_logs
      set resource_type = coalesce(resource_type, table_name, 'unknown')
      where resource_type is null
    $sql$;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'audit_logs'
      and column_name = 'record_id'
  ) then
    execute $sql$
      update public.audit_logs
      set resource_id = coalesce(resource_id, record_id, '')
      where resource_id is null
    $sql$;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'audit_logs'
      and column_name = 'old_values'
  ) then
    execute $sql$
      update public.audit_logs
      set metadata = coalesce(metadata, jsonb_build_object('old_values', old_values, 'new_values', new_values))
      where metadata is null
    $sql$;
  end if;
end;
$$;

create index if not exists idx_audit_logs_user_id
  on public.audit_logs (user_id);
create index if not exists idx_audit_logs_resource
  on public.audit_logs (resource_type, resource_id);
create index if not exists idx_audit_logs_created_at
  on public.audit_logs (created_at desc);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete set null,
  customer_email varchar(191),
  customer_phone varchar(32),
  notification_type text not null check (notification_type in ('booking_confirmation', 'booking_reminder', 'booking_cancellation', 'status_update', 'offer_promotion')),
  template_name varchar(100) not null,
  channel text not null default 'email' check (channel in ('email', 'sms', 'whatsapp', 'in_app')),
  subject varchar(255),
  body text,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'bounced')),
  retry_count int not null default 0,
  sent_at timestamptz,
  failed_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_notifications_booking_id
  on public.notifications (booking_id);
create index if not exists idx_notifications_status
  on public.notifications (status);
create index if not exists idx_notifications_created_at
  on public.notifications (created_at desc);

drop trigger if exists trigger_notifications_touch_updated_at on public.notifications;
create trigger trigger_notifications_touch_updated_at
before update on public.notifications
for each row
execute function public.touch_updated_at();

create table if not exists public.customer_preferences (
  id bigint generated by default as identity primary key,
  customer_phone varchar(32) not null unique,
  customer_email varchar(191) unique,
  customer_name varchar(120),
  preferred_service varchar(160),
  preferred_time varchar(32),
  preferred_date_day varchar(15),
  preferred_contact_method text not null default 'phone' check (preferred_contact_method in ('phone', 'email', 'sms', 'whatsapp')),
  total_bookings int not null default 0,
  total_spent numeric(10,2) not null default 0,
  loyalty_points int not null default 0,
  last_booking_date date,
  opt_in_promotions boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_customer_preferences_phone
  on public.customer_preferences (customer_phone);
create index if not exists idx_customer_preferences_email
  on public.customer_preferences (customer_email);

drop trigger if exists trigger_customer_preferences_touch_updated_at on public.customer_preferences;
create trigger trigger_customer_preferences_touch_updated_at
before update on public.customer_preferences
for each row
execute function public.touch_updated_at();

create table if not exists public.email_templates (
  id bigint generated by default as identity primary key,
  template_name varchar(100) not null unique,
  subject varchar(255) not null,
  body text not null,
  variables jsonb,
  is_active boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now()
);

create index if not exists idx_email_templates_name
  on public.email_templates (template_name);

drop trigger if exists trigger_email_templates_touch_updated_at on public.email_templates;
create trigger trigger_email_templates_touch_updated_at
before update on public.email_templates
for each row
execute function public.touch_updated_at();

-- ============================================
-- CMS CONTENT TABLES
-- ============================================

create table if not exists public.hero_content (
  id bigint generated by default as identity primary key,
  heading text not null default '',
  subtitle text not null default '',
  primary_cta_label text not null default 'Book Appointment',
  primary_cta_url text not null default '/booking',
  secondary_cta_label text not null default 'View Services',
  secondary_cta_url text not null default '/services',
  hero_image_url text,
  hero_image_alt text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_hero_content_touch_updated_at on public.hero_content;
create trigger trigger_hero_content_touch_updated_at
before update on public.hero_content
for each row
execute function public.touch_updated_at();

create table if not exists public.about_content (
  id bigint generated by default as identity primary key,
  headline text not null default '',
  body text not null default '',
  bullet_points jsonb not null default '[]'::jsonb,
  founder_name text not null default '',
  founder_title text not null default '',
  founder_image_url text,
  gallery_image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_about_content_touch_updated_at on public.about_content;
create trigger trigger_about_content_touch_updated_at
before update on public.about_content
for each row
execute function public.touch_updated_at();

create table if not exists public.contact_settings (
  id bigint generated by default as identity primary key,
  phone text not null default '',
  whatsapp text not null default '',
  email text not null default '',
  address text not null default '',
  map_url text not null default '',
  working_hours text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_contact_settings_touch_updated_at on public.contact_settings;
create trigger trigger_contact_settings_touch_updated_at
before update on public.contact_settings
for each row
execute function public.touch_updated_at();

create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  instagram text,
  facebook text,
  youtube text,
  whatsapp text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_social_links_touch_updated_at on public.social_links;
create trigger trigger_social_links_touch_updated_at
before update on public.social_links
for each row
execute function public.touch_updated_at();

create table if not exists public.seo_settings (
  id bigint generated by default as identity primary key,
  meta_title text not null default '',
  meta_description text not null default '',
  keywords text not null default '',
  canonical_url text not null default '',
  og_image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trigger_seo_settings_touch_updated_at on public.seo_settings;
create trigger trigger_seo_settings_touch_updated_at
before update on public.seo_settings
for each row
execute function public.touch_updated_at();

create table if not exists public.pricing_packages (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  price numeric(10,2) not null default 0,
  popular boolean not null default false,
  features_text text not null default '',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_pricing_packages_active
  on public.pricing_packages (is_active)
  where deleted_at is null;
create index if not exists idx_pricing_packages_sort_order
  on public.pricing_packages (sort_order)
  where deleted_at is null;

drop trigger if exists trigger_pricing_packages_touch_updated_at on public.pricing_packages;
create trigger trigger_pricing_packages_touch_updated_at
before update on public.pricing_packages
for each row
execute function public.touch_updated_at();

create table if not exists public.faq_sections (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  slug varchar(120) not null unique,
  description text not null,
  items_text text not null default '',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_faq_sections_active
  on public.faq_sections (is_active)
  where deleted_at is null;
create index if not exists idx_faq_sections_sort_order
  on public.faq_sections (sort_order)
  where deleted_at is null;

drop trigger if exists trigger_faq_sections_touch_updated_at on public.faq_sections;
create trigger trigger_faq_sections_touch_updated_at
before update on public.faq_sections
for each row
execute function public.touch_updated_at();

create table if not exists public.service_areas (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  summary text not null,
  search_intent text not null,
  highlights_text text not null default '',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_service_areas_active
  on public.service_areas (is_active)
  where deleted_at is null;
create index if not exists idx_service_areas_sort_order
  on public.service_areas (sort_order)
  where deleted_at is null;

drop trigger if exists trigger_service_areas_touch_updated_at on public.service_areas;
create trigger trigger_service_areas_touch_updated_at
before update on public.service_areas
for each row
execute function public.touch_updated_at();

create table if not exists public.blog_categories (
  slug varchar(120) primary key,
  title varchar(160) not null,
  description text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_blog_categories_active
  on public.blog_categories (is_active)
  where deleted_at is null;
create index if not exists idx_blog_categories_sort_order
  on public.blog_categories (sort_order)
  where deleted_at is null;

drop trigger if exists trigger_blog_categories_touch_updated_at on public.blog_categories;
create trigger trigger_blog_categories_touch_updated_at
before update on public.blog_categories
for each row
execute function public.touch_updated_at();

create table if not exists public.blog_authors (
  slug varchar(120) primary key,
  name varchar(160) not null,
  bio text,
  avatar_url varchar(255),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_blog_authors_active
  on public.blog_authors (is_active)
  where deleted_at is null;

drop trigger if exists trigger_blog_authors_touch_updated_at on public.blog_authors;
create trigger trigger_blog_authors_touch_updated_at
before update on public.blog_authors
for each row
execute function public.touch_updated_at();

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug varchar(180) not null unique,
  title varchar(255) not null,
  excerpt text not null,
  content_text text not null,
  featured_image_url varchar(255),
  tags_text text,
  category_slug varchar(120) not null references public.blog_categories(slug) on update cascade on delete restrict,
  author_slug varchar(120) not null references public.blog_authors(slug) on update cascade on delete restrict,
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  seo_title varchar(255),
  seo_description text,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_blog_posts_published
  on public.blog_posts (is_published, published_at desc)
  where deleted_at is null;
create index if not exists idx_blog_posts_category
  on public.blog_posts (category_slug)
  where deleted_at is null;
create index if not exists idx_blog_posts_author
  on public.blog_posts (author_slug)
  where deleted_at is null;
create index if not exists idx_blog_posts_featured
  on public.blog_posts (is_featured)
  where deleted_at is null;

drop trigger if exists trigger_blog_posts_touch_updated_at on public.blog_posts;
create trigger trigger_blog_posts_touch_updated_at
before update on public.blog_posts
for each row
execute function public.touch_updated_at();

insert into public.blog_categories (slug, title, description, sort_order, is_active)
values
  ('bridal', 'Bridal', 'Bridal makeup guidance and wedding day preparation.', 1, true),
  ('academy', 'Academy', 'Beauty education, training and certification insights.', 2, true),
  ('skincare', 'Skincare', 'Pre-bridal and event skincare routines.', 3, true),
  ('beauty-tips', 'Beauty Tips', 'Practical everyday beauty and glam tips.', 4, true),
  ('local-seo', 'Local SEO', 'Local visibility and discovery content.', 5, true)
on conflict (slug) do nothing;

insert into public.blog_authors (slug, name, bio, avatar_url, is_active)
values
  (
    'rasmirekha-swain',
    'Rasmirekha Swain',
    'Founder of Elegance Makeover & Academy and lead bridal artist in Jajpur Road, Odisha.',
    null,
    true
  )
on conflict (slug) do nothing;

insert into public.blog_posts (
  slug,
  title,
  excerpt,
  content_text,
  featured_image_url,
  tags_text,
  category_slug,
  author_slug,
  published_at,
  updated_at,
  seo_title,
  seo_description,
  is_featured,
  is_published,
  sort_order
)
values
  (
    'bridal-makeup-checklist-jajpur-road',
    'Bridal Makeup Checklist for Jajpur Road Weddings',
    'Use this checklist to plan your bridal prep, timing, product choices and final touch-ups.',
    $$Start with a trial look if your wedding date allows it. Trials reduce uncertainty and help align your makeup with jewelry, outfit and lighting.

Prepare skin in the days before the event with hydration, gentle cleansing and no harsh experiments. Good skin prep matters as much as product quality.

On the day itself, keep your accessories, outfit references and any allergy notes ready so the artist can work faster and more precisely.

For a polished finish, combine makeup with hair styling and draping instead of treating them as separate last-minute tasks.$$,
    null,
    'bridal makeup Jajpur Road,bridal checklist,wedding makeup Odisha',
    'bridal',
    'rasmirekha-swain',
    '2026-06-03T00:00:00Z',
    now(),
    'Bridal Makeup Checklist for Jajpur Road Weddings',
    'A practical bridal checklist for brides planning a refined, long-lasting wedding look in Odisha.',
    true,
    true,
    1
  ),
  (
    'how-to-choose-makeup-academy-odisha',
    'How to Choose a Makeup Academy in Odisha',
    'What to look for in academy training, certifications, live practice and placement support.',
    $$Look for a curriculum that covers skin prep, base work, eye design, hair basics and client handling. A useful course should build both skill and confidence.

Ask whether the academy offers live demonstrations and supervised practice on models or real clients. That experience is often what separates a course from a certificate.

Placement support and portfolio guidance are important signals that the academy is serious about student outcomes.

If you are local to Odisha, choosing a nearby academy can make attendance and follow-up practice much easier.$$,
    null,
    'makeup academy Odisha,beauty course,certified makeup training',
    'academy',
    'rasmirekha-swain',
    '2026-06-03T00:00:00Z',
    now(),
    'How to Choose a Makeup Academy in Odisha',
    'What to look for in academy training, certifications, live practice and placement support.',
    false,
    true,
    2
  ),
  (
    'pre-bridal-skincare-routine-before-wedding',
    'Pre-Bridal Skincare Routine Before the Wedding',
    'A simple, high-impact skincare routine to prepare for bridal makeup and photography.',
    $$Keep skincare simple in the final two weeks. Hydration, gentle cleansing and sun protection usually matter more than adding new aggressive treatments.

Avoid trying multiple new products right before the wedding. A stable routine reduces the risk of irritation or unexpected breakouts.

Book facial or cleanup services with enough time before the final bridal appointment so skin has time to settle naturally.

If your skin has any sensitivity, tell the artist early so the makeup plan can be adjusted.$$,
    null,
    'pre bridal skincare,wedding skincare routine,skin prep before wedding',
    'skincare',
    'rasmirekha-swain',
    '2026-06-03T00:00:00Z',
    now(),
    'Pre-Bridal Skincare Routine Before the Wedding',
    'A simple, high-impact skincare routine to prepare for bridal makeup and photography.',
    false,
    true,
    3
  ),
  (
    'party-makeup-vs-bridal-makeup',
    'Party Makeup vs Bridal Makeup: What is the Difference?',
    'Understand how bridal and party looks differ in finish, timing, durability and product selection.',
    $$Party makeup is often lighter and quicker, while bridal makeup is designed to last longer and look balanced across many photo conditions.

Bridal looks usually need stronger base work, more precise structure and a higher focus on longevity.

For receptions or day events, a softer party look can be the better choice if the event does not require all-day wear.

A good artist will suggest the right option based on your event, not simply push the most expensive package.$$,
    null,
    'party makeup,bridal makeup difference,makeup tips',
    'beauty-tips',
    'rasmirekha-swain',
    '2026-06-03T00:00:00Z',
    now(),
    'Party Makeup vs Bridal Makeup: What is the Difference?',
    'Understand how bridal and party looks differ in finish, timing, durability and product selection.',
    false,
    true,
    4
  )
on conflict (slug) do nothing;

insert into public.pricing_packages (name, price, popular, features_text, sort_order, is_active)
values
  (
    'Classic Bride',
    6000,
    false,
    'Signature bridal makeup
Polished hair styling
3-hour appointment window
Basic touch-up support
One attendant consultation',
    1,
    true
  ),
  (
    'Royal Bride',
    8000,
    true,
    'Premium bridal makeup
Luxury hair design and draping
4-hour appointment window
2 complimentary touch-ups
Bride''s mother makeup included
Trial session included',
    2,
    true
  ),
  (
    'Maharani Bride',
    12000,
    false,
    'Haute couture bridal makeup
Editorial hair styling
4+ hour appointment window
Unlimited touch-up support
Family member makeup
Dress consultation
Pre-wedding shoot coordination',
    3,
    true
  )
on conflict do nothing;

create index if not exists idx_hero_content_active
  on public.hero_content (is_active);
create index if not exists idx_about_content_active
  on public.about_content (is_active);
create index if not exists idx_contact_settings_active
  on public.contact_settings (is_active);
create index if not exists idx_social_links_active
  on public.social_links (is_active);
create index if not exists idx_seo_settings_active
  on public.seo_settings (is_active);

-- ============================================
-- VIEWS
-- ============================================

create or replace view public.upcoming_bookings as
select
  b.id,
  b.booking_code,
  b.customer_name,
  b.phone,
  b.email,
  b.service_name,
  b.booking_date,
  b.booking_time,
  b.duration_minutes,
  b.status,
  b.source,
  cp.preferred_contact_method,
  s.duration_label,
  s.category
from public.bookings b
left join public.customer_preferences cp on b.phone = cp.customer_phone
left join public.services s on b.service_id = s.id
where b.deleted_at is null
  and b.booking_date >= current_date
  and b.status not in ('rejected', 'cancelled')
order by b.booking_date, b.booking_time;

create or replace view public.booking_stats as
select 'Total Bookings' as metric, count(*) as value
from public.bookings
where deleted_at is null
union all
select 'Approved Bookings', count(*)
from public.bookings
where deleted_at is null and status = 'approved'
union all
select 'Pending Bookings', count(*)
from public.bookings
where deleted_at is null and status = 'pending'
union all
select 'Unique Customers', count(distinct phone)
from public.bookings
where deleted_at is null
union all
select 'Total Revenue', coalesce(sum(amount_paid), 0)::bigint
from public.bookings
where deleted_at is null and status = 'completed';

create or replace view public.service_popularity as
select
  s.id,
  s.title,
  s.category,
  count(b.id) as booking_count,
  count(b.id) * 100.0 / nullif(sum(count(b.id)) over (), 0) as percentage,
  coalesce(sum(b.amount_paid), 0) as revenue_generated
from public.services s
left join public.bookings b
  on s.id = b.service_id and b.deleted_at is null
where s.deleted_at is null
group by s.id, s.title, s.category
order by booking_count desc;

create or replace view public.customer_engagement as
select
  cp.customer_phone,
  cp.customer_email,
  cp.customer_name,
  cp.total_bookings,
  cp.total_spent,
  cp.loyalty_points,
  cp.last_booking_date,
  case
    when cp.total_bookings >= 5 then 'VIP'
    when cp.total_bookings >= 3 then 'Regular'
    else 'New'
  end as customer_tier,
  case
    when cp.last_booking_date < current_date - interval '90 days' then 'Inactive'
    when cp.last_booking_date < current_date - interval '30 days' then 'At Risk'
    else 'Active'
  end as engagement_status
from public.customer_preferences cp
order by cp.total_spent desc;

create or replace view public.recent_activity as
select
  'booking' as activity_type,
  b.booking_code as entity_id,
  b.customer_name as description,
  b.status as status,
  b.updated_at as activity_date
from public.bookings b
where b.deleted_at is null
union all
select
  'testimonial',
  t.id::text,
  concat(t.customer_name, ' - ', t.service_name),
  t.status,
  t.updated_at
from public.testimonials t
where t.deleted_at is null
union all
select
  'offer',
  o.id::text,
  o.title,
  o.status,
  o.updated_at
from public.offers o
where o.deleted_at is null
order by activity_date desc
limit 50;

create or replace view public.notification_queue_status as
select
  notification_type,
  channel,
  status,
  count(*) as count,
  count(*) filter (where created_at > now() - interval '24 hours') as last_24h
from public.notifications
group by notification_type, channel, status
order by notification_type, channel;

create or replace view public.revenue_summary as
select
  b.booking_date,
  count(*) as booking_count,
  coalesce(sum(b.amount_quoted), 0) as quoted_amount,
  coalesce(sum(b.amount_paid), 0) as received_amount,
  coalesce(sum(coalesce(b.amount_quoted, 0) - coalesce(b.amount_paid, 0)), 0) as pending_amount,
  count(*) filter (where b.payment_status = 'paid') as paid_count,
  count(*) filter (where b.payment_status = 'unpaid') as unpaid_count
from public.bookings b
where b.deleted_at is null and b.status = 'completed'
group by b.booking_date
order by b.booking_date desc;

-- ============================================
-- FUNCTIONS
-- ============================================

create or replace function public.generate_booking_code()
returns varchar
language plpgsql
as $$
declare
  new_code varchar;
  attempt_count int := 0;
begin
  loop
    new_code := 'EM-' || to_char(current_date, 'YYMMDD') || '-' || lpad((floor(random() * 9000) + 1000)::text, 4, '0');
    if not exists (select 1 from public.bookings where booking_code = new_code) then
      return new_code;
    end if;

    attempt_count := attempt_count + 1;
    if attempt_count > 1000 then
      raise exception 'Could not generate unique booking code';
    end if;
  end loop;
end;
$$;

create or replace function public.update_customer_preferences()
returns trigger
language plpgsql
as $$
begin
  if new.deleted_at is null and new.status = 'completed' then
    if tg_op = 'INSERT' or old.status is distinct from new.status then
      insert into public.customer_preferences (
        customer_phone,
        customer_email,
        customer_name,
        total_bookings,
        total_spent,
        last_booking_date
      ) values (
        new.phone,
        new.email,
        new.customer_name,
        1,
        coalesce(new.amount_paid, 0),
        new.booking_date
      )
      on conflict (customer_phone) do update set
        customer_email = coalesce(excluded.customer_email, public.customer_preferences.customer_email),
        customer_name = excluded.customer_name,
        total_bookings = public.customer_preferences.total_bookings + 1,
        total_spent = public.customer_preferences.total_spent + coalesce(excluded.total_spent, 0),
        last_booking_date = excluded.last_booking_date,
        updated_at = now();
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trigger_update_customer_preferences on public.bookings;
create trigger trigger_update_customer_preferences
after insert or update of status on public.bookings
for each row
execute function public.update_customer_preferences();

create or replace function public.trigger_notifications_on_booking_update()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'UPDATE' and old.status is distinct from new.status then
    insert into public.notifications (
      booking_id,
      customer_email,
      customer_phone,
      notification_type,
      template_name,
      channel,
      status
    ) values (
      new.id,
      new.email,
      new.phone,
      'status_update',
      'booking_status_changed',
      'email',
      'pending'
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trigger_booking_notifications on public.bookings;
create trigger trigger_booking_notifications
after update on public.bookings
for each row
execute function public.trigger_notifications_on_booking_update();

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

create or replace function public.current_admin_user_id()
returns uuid
language sql
stable
as $$
  select au.id
  from public.admin_users au
  where au.auth_user_id = auth.uid()
    and au.is_active = true
  limit 1
$$;

create or replace function public.current_admin_role()
returns text
language sql
stable
as $$
  select coalesce((
    select au.role
    from public.admin_users au
    where au.auth_user_id = auth.uid()
      and au.is_active = true
    limit 1
  ), '')
$$;

create or replace function public.is_authenticated_admin()
returns boolean
language sql
stable
as $$
  select public.current_admin_user_id() is not null
$$;

alter table public.admin_users enable row level security;
alter table public.audit_logs enable row level security;
alter table public.rate_limits enable row level security;

drop policy if exists "admin users read by admins" on public.admin_users;
create policy "admin users read by admins"
on public.admin_users
for select
using (public.is_authenticated_admin());

drop policy if exists "admin users manage by super admin" on public.admin_users;
create policy "admin users manage by super admin"
on public.admin_users
for all
using (public.current_admin_role() = 'super_admin')
with check (public.current_admin_role() = 'super_admin');

drop policy if exists "audit logs read by admins" on public.audit_logs;
create policy "audit logs read by admins"
on public.audit_logs
for select
using (public.is_authenticated_admin());

drop policy if exists "audit logs insert by admins" on public.audit_logs;
create policy "audit logs insert by admins"
on public.audit_logs
for insert
with check (public.is_authenticated_admin());

drop policy if exists "rate limits by admins" on public.rate_limits;
create policy "rate limits by admins"
on public.rate_limits
for all
using (public.is_authenticated_admin())
with check (public.is_authenticated_admin());
