-- ==============================================================================
-- ELEGANCE MAKEOVER & ACADEMY — COMPLETE SUPABASE SEO & CONTENT MIGRATION
-- File: docs/seo-migration.sql
-- Instructions: Copy and paste this ENTIRE script into the Supabase SQL Editor
--               and click "Run". It is 100% idempotent and safe to run on both
--               fresh and existing databases.
-- ==============================================================================

-- 0. UTILITIES & EXTENSIONS
create extension if not exists pgcrypto;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ==============================================================================
-- 1. SERVICES TABLE (SEO & METADATA ENHANCEMENT)
-- ==============================================================================

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title varchar(160) not null,
  category text not null check (category in ('bridal', 'parlour', 'academy')),
  description text not null,
  price_label varchar(64) not null,
  price_min numeric(10,2),
  price_max numeric(10,2),
  duration_label varchar(64) not null,
  duration_minutes int,
  featured boolean not null default false,
  image_url varchar(255),
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_by bigint,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.services
  add column if not exists slug varchar(160),
  add column if not exists meta_title varchar(160),
  add column if not exists meta_description text,
  add column if not exists og_image varchar(255),
  add column if not exists faq_json jsonb default '[]'::jsonb;

-- Populate default slugs for any pre-existing services
update public.services set slug = 'bridal-makeup' where slug is null and lower(title) like '%bridal%' and lower(title) not like '%airbrush%';
update public.services set slug = 'hd-airbrush-bridal-makeup' where slug is null and lower(title) like '%airbrush%';
update public.services set slug = 'engagement-makeup' where slug is null and lower(title) like '%engagement%';
update public.services set slug = 'party-makeup' where slug is null and lower(title) like '%party%';
update public.services set slug = 'hair-styling' where slug is null and lower(title) like '%hair%' and lower(title) not like '%smoothen%';
update public.services set slug = 'hydra-facial' where slug is null and (lower(title) like '%facial%' or lower(title) like '%hydra%');
update public.services set slug = 'hair-smoothening' where slug is null and lower(title) like '%smoothen%';
update public.services set slug = 'makeup-academy-course' where slug is null and (lower(title) like '%academy%' or lower(title) like '%course%');
update public.services set slug = 'service-' || id where slug is null;

-- Deduplicate any duplicate slugs before unique indexing
with duplicates as (
  select id, row_number() over (partition by slug order by id) as rnum
  from public.services
  where slug is not null
)
update public.services s
set slug = s.slug || '-' || s.id
from duplicates d
where s.id = d.id and d.rnum > 1;

-- Drop legacy partial index/constraint and create unconditional unique index for ON CONFLICT
alter table public.services drop constraint if exists services_slug_key;
drop index if exists public.idx_services_slug;
create unique index if not exists idx_services_slug on public.services (slug);

-- Ensure 8 primary SEO services exist with rich metadata
insert into public.services (
  slug, title, category, description, price_label, price_min, price_max,
  duration_label, duration_minutes, featured, meta_title, meta_description, is_active, sort_order
)
values
  (
    'bridal-makeup',
    'Bridal Makeup',
    'bridal',
    'Signature bespoke bridal makeover blending modern luxury HD cosmetics with authentic Odia traditions, mukut balancing, and ceremonial longevity.',
    '₹8,000 - ₹12,000',
    8000, 12000,
    '3 - 3.5 Hours',
    210,
    true,
    'Bridal Makeup Artist in Jajpur Road | Elegance Makeover',
    'Award-winning bridal makeup in Jajpur Road, Odisha by Rasmirekha Swain. Traditional Odia bridal styling, mukut fitting & 16-hr waterproof HD artistry.',
    true,
    1
  ),
  (
    'hd-airbrush-bridal-makeup',
    'HD Airbrush Bridal Makeup',
    'bridal',
    'Flawless micro-spray silicone airbrush formulation engineered for high-humidity coastal climates, tear-resistance, and 4K wedding cinematography.',
    '₹12,000 - ₹16,000',
    12000, 16000,
    '3.5 - 4 Hours',
    240,
    true,
    'HD Airbrush Bridal Makeup in Odisha | 24-Hr Waterproof',
    'Premier HD Airbrush bridal makeup in Odisha by Master Artist Rasmirekha Swain. 100% waterproof, sweatproof, and camera-ready 4K high-definition finish.',
    true,
    2
  ),
  (
    'engagement-makeup',
    'Engagement & Ring Ceremony Makeup',
    'bridal',
    'Soft-glam radiant makeover designed for evening lighting, ring exchanges, and engagement photography with bespoke hair and floral accents.',
    '₹5,000 - ₹8,000',
    5000, 8000,
    '2 - 2.5 Hours',
    150,
    true,
    'Engagement Makeup Artist in Jajpur Road | Ring Ceremony Glam',
    'Elegant engagement makeup in Jajpur Road, Odisha. Soft-glam glowing base, bespoke hair styling & custom lash extensions by Master Artist Rasmirekha.',
    true,
    3
  ),
  (
    'party-makeup',
    'Party & Reception Makeup',
    'parlour',
    'High-impact celebrity glam for bridesmaids, wedding guests, reception parties, and festive celebrations with long-wear finish.',
    '₹3,000 - ₹5,000',
    3000, 5000,
    '1.5 - 2 Hours',
    100,
    false,
    'Party Makeup in Jajpur Road | Sangeet & Reception Glam',
    'Glamorous party and reception makeup in Jajpur Road, Odisha. Long-lasting HD base, smoky eyes, and contemporary hair design for wedding guests.',
    true,
    4
  ),
  (
    'hair-styling',
    'Bridal & Event Hair Styling',
    'parlour',
    'Bespoke hair design from classical jasmine gajra buns with mukut anchors to textured modern Hollywood waves and floral braid artistry.',
    '₹1,500 - ₹3,500',
    1500, 3500,
    '1 - 1.5 Hours',
    75,
    false,
    'Bridal Hair Styling in Jajpur Road | Gajra & Modern Buns',
    'Professional bridal hair styling in Jajpur Road, Odisha. Classic Odia bridal buns, fresh jasmine gajra placement, mukut anchoring & reception waves.',
    true,
    5
  ),
  (
    'hydra-facial',
    'Clinical Hydra Glow Facial',
    'parlour',
    'Medical-grade vortex extraction and dermal infusion treatment designed to unclog pores, eliminate blackheads, and hydrate skin for an instant bridal glow.',
    '₹2,500 - ₹4,500',
    2500, 4500,
    '60 - 75 Mins',
    60,
    false,
    'Hydra Facial in Jajpur Road | Instant Glass Skin Glow',
    'Medical-grade Hydra Facial in Jajpur Road, Odisha. Deep pore vacuum extraction, antioxidant infusion & deep barrier hydration for brides and clients.',
    true,
    6
  ),
  (
    'hair-smoothening',
    'Hair Smoothening & Keratin',
    'parlour',
    'Formaldehyde-free salon treatment providing mirror-shine, frizz-free straightness, and thermal protection lasting 6 to 9 months.',
    '₹4,500 - ₹8,500',
    4500, 8500,
    '3 - 4 Hours',
    210,
    false,
    'Hair Smoothening & Keratin in Jajpur Road | Frizz-Free Shine',
    'Professional hair smoothening, keratin & nanoplastia in Jajpur Road, Odisha. Long-lasting silky straight hair with salon-grade nourishment.',
    true,
    7
  ),
  (
    'makeup-academy-course',
    'Professional Makeup Artist Course',
    'academy',
    'Comprehensive master certification program with live model practice, vanity lighting mastery, bridal draping, and business client development.',
    '₹35,000 - ₹50,000',
    35000, 50000,
    '6 - 12 Weeks',
    4800,
    true,
    'Makeup Artist Academy Course in Odisha | Certification',
    'Government-certified professional makeup artist course in Jajpur Road, Odisha. Learn bridal HD, airbrush, hairstyling & business skills from Rasmirekha.',
    true,
    8
  )
on conflict (slug) do update set
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  price_label = excluded.price_label,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  duration_label = excluded.duration_label,
  duration_minutes = excluded.duration_minutes,
  featured = excluded.featured,
  updated_at = now();

-- ==============================================================================
-- 2. SERVICE AREAS TABLE (PROGRAMMATIC LOCAL LANDING PAGES)
-- ==============================================================================

create table if not exists public.service_areas (
  id bigint generated by default as identity primary key,
  slug varchar(160),
  name varchar(160) not null,
  summary text not null,
  search_intent text,
  highlights_text text,
  meta_title varchar(160),
  meta_description text,
  og_image varchar(255),
  faq_json jsonb default '[]'::jsonb,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.service_areas
  add column if not exists slug varchar(160),
  add column if not exists meta_title varchar(160),
  add column if not exists meta_description text,
  add column if not exists og_image varchar(255),
  add column if not exists faq_json jsonb default '[]'::jsonb;

-- Populate slugs for existing records if present
update public.service_areas set slug = 'jajpur-road' where slug is null and lower(name) like '%jajpur road%';
update public.service_areas set slug = 'vyasanagar' where slug is null and lower(name) like '%vyasanagar%';
update public.service_areas set slug = 'jajpur-town' where slug is null and lower(name) like '%jajpur town%';
update public.service_areas set slug = 'danagadi' where slug is null and lower(name) like '%danagadi%';
update public.service_areas set slug = 'kalinganagar' where slug is null and lower(name) like '%kalinganagar%';
update public.service_areas set slug = 'panikoili' where slug is null and lower(name) like '%panikoili%';
update public.service_areas set slug = 'kuakhia' where slug is null and lower(name) like '%kuakhia%';
update public.service_areas set slug = 'bhadrak' where slug is null and lower(name) like '%bhadrak%';
update public.service_areas set slug = 'cuttack' where slug is null and lower(name) like '%cuttack%';
update public.service_areas set slug = 'bhubaneswar' where slug is null and lower(name) like '%bhubaneswar%';
update public.service_areas set slug = 'area-' || id where slug is null;

-- Deduplicate any duplicate slugs before unique indexing
with duplicates as (
  select id, row_number() over (partition by slug order by id) as rnum
  from public.service_areas
  where slug is not null
)
update public.service_areas sa
set slug = sa.slug || '-' || sa.id
from duplicates d
where sa.id = d.id and d.rnum > 1;

-- Drop legacy partial index/constraint and create unconditional unique index for ON CONFLICT
alter table public.service_areas drop constraint if exists service_areas_slug_key;
drop index if exists public.idx_service_areas_slug;
drop index if exists public.idx_service_areas_slug_unique;
create unique index if not exists idx_service_areas_slug on public.service_areas (slug);

-- Upsert all 10 priority service areas
insert into public.service_areas (
  slug, name, summary, search_intent, highlights_text, meta_title, meta_description, sort_order, is_active
)
values
  (
    'jajpur-road',
    'Jajpur Road',
    'Flagship studio base and premier bridal academy salon. Instant appointment confirmations, bridal trials, and walk-in parlour services.',
    'Bridal makeup artist, beauty parlour, and makeup academy in Jajpur Road.',
    'Studio base & flagship academy\nWalk-in & bridal trials\nSame-day booking coordination',
    'Bridal Makeup Artist in Jajpur Road | Elegance Makeover',
    'Premier bridal makeup artist in Jajpur Road, Odisha. Master Artist Rasmirekha Swain offers luxury HD & Airbrush bridal makeover, parlour services & academy.',
    1,
    true
  ),
  (
    'vyasanagar',
    'Vyasanagar',
    'Direct municipal twin city to Jajpur Road. Fast venue dispatch for morning lagna rituals, reception styling, and party makeovers.',
    'Bridal makeup artist in Vyasanagar Odisha and beauty parlour services.',
    '5-10 min venue arrival\nMulti-person bridesmaid packages\nCustom Odia bridal drapes',
    'Bridal Makeup Artist in Vyasanagar | Elegance Makeover',
    'Top bridal makeup artist in Vyasanagar, Odisha. Master Artist Rasmirekha Swain delivers luxury HD & Airbrush wedding styling with 10-min venue arrival.',
    2,
    true
  ),
  (
    'jajpur-town',
    'Jajpur Town',
    'Heritage hub of the Biraja Temple. Full bridal entourage styling, mandap touchups, and sacred ritual longevity makeup.',
    'Bridal makeup artist in Jajpur Town near Biraja Temple.',
    'Biraja Kshetra wedding expertise\nHigh-humidity smudge resistance\nRitual-proof makeup',
    'Bridal Makeup Artist in Jajpur Town | Biraja Kshetra Makeovers',
    'Bespoke bridal makeover in Jajpur Town, Odisha by Rasmirekha Swain. Traditional Odia bridal styling, mukut fitting & 100% waterproof airbrush makeup.',
    3,
    true
  ),
  (
    'danagadi',
    'Danagadi',
    'Rapid on-venue service for industrial corridor wedding banquets, family ceremonies, and bridal party transformations.',
    'Bridal makeup artist in Danagadi and pre-wedding parlour services.',
    'Fast corridor travel\nComplete vanity mobile kit\nPre-bridal packages',
    'Bridal Makeup Artist in Danagadi | Elegance Makeover',
    'Luxury bridal makeup in Danagadi, Odisha. Professional artist travel for weddings, engagements & reception glam. Book Master Artist Rasmirekha Swain.',
    4,
    true
  ),
  (
    'kalinganagar',
    'Kalinganagar',
    'Corporate township weddings, guest house banquets, and high-glam evening receptions with premium HD airbrush styling.',
    'Bridal makeup in Kalinganagar Tata Steel township area.',
    'Township venue travel\nEvening reception glam\nHD longwear formulations',
    'Bridal Makeup Artist in Kalinganagar | Luxury Wedding Glam',
    'Premier bridal makeup in Kalinganagar, Odisha. On-venue luxury styling for Tata Steel township banquets, receptions & pre-bridal services by Rasmirekha.',
    5,
    true
  ),
  (
    'panikoili',
    'Panikoili',
    'Highway junction kalyan mandap weddings with punctual early morning travel and full bridal beauty kits.',
    'Bridal makeup artist in Panikoili Odisha near NH16.',
    'NH16 highway connectivity\nEarly morning call time\nAirbrush & HD packages',
    'Bridal Makeup Artist in Panikoili | Elegance Makeover',
    'Expert bridal makeup in Panikoili, Odisha near NH16. Punctual venue travel, high-durability HD airbrush cosmetics & saree draping for wedding muhurats.',
    6,
    true
  ),
  (
    'kuakhia',
    'Kuakhia',
    'South Jajpur wedding destinations, family celebrations, and traditional bride makeovers with bespoke jewellery setting.',
    'Bridal makeup artist in Kuakhia and wedding parlour services.',
    'Bespoke jewellery styling\nSaree draping specialists\nPre-wedding trial availability',
    'Bridal Makeup Artist in Kuakhia | Elegance Makeover',
    'Bespoke bridal makeup artist in Kuakhia, Odisha. Traditional Odia wedding makeover, jewellery placement & camera-ready finishes by Master Artist Rasmirekha.',
    7,
    true
  ),
  (
    'bhadrak',
    'Bhadrak',
    'Regular destination for brides and families traveling or booking Master Artist Rasmirekha Swain for high-end wedding artistry.',
    'Bridal makeup artist in Bhadrak and luxury wedding styling.',
    'Outstation bridal crew\n45-min transit connectivity\nMulti-event wedding booking',
    'Bridal Makeup Artist in Bhadrak | Luxury Wedding Makeover',
    'Top bridal makeup artist for Bhadrak weddings. Master Artist Rasmirekha Swain travels directly to your venue for luxury HD Airbrush bridal makeovers.',
    8,
    true
  ),
  (
    'cuttack',
    'Cuttack',
    'Silver City brides booking luxury HD airbrush makeup and aspiring students enrolling in professional makeup certification.',
    'Bridal makeup artist Cuttack and professional makeup academy.',
    'Grand heritage venue styling\nAcademy certification courses\nComprehensive bridal kits',
    'Bridal Makeup Artist in Cuttack | Luxury Wedding & Academy',
    'Luxury bridal makeup artist serving Cuttack, Odisha. High-definition airbrush bridal styling & certified makeup academy courses by Rasmirekha Swain.',
    9,
    true
  ),
  (
    'bhubaneswar',
    'Bhubaneswar',
    'Odisha capital destination weddings, luxury 5-star hotel receptions, and advanced masterclass students.',
    'Luxury bridal makeup artist Bhubaneswar and advanced makeup academy.',
    'Luxury hotel wedding artistry\n5-star banquet styling\nStatewide academy reputation',
    'Bridal Makeup Artist in Bhubaneswar | Luxury Wedding Artistry',
    'Celebrated bridal makeup artist serving Bhubaneswar destination weddings & 5-star receptions. Flawless 4K airbrush artistry by Rasmirekha Swain.',
    10,
    true
  )
on conflict (slug) do update set
  name = excluded.name,
  summary = excluded.summary,
  search_intent = excluded.search_intent,
  highlights_text = excluded.highlights_text,
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

drop trigger if exists trigger_service_areas_touch_updated_at on public.service_areas;
create trigger trigger_service_areas_touch_updated_at
before update on public.service_areas
for each row
execute function public.touch_updated_at();

-- ==============================================================================
-- 3. BLOG POSTS, CATEGORIES & AUTHOR (E-E-A-T CORNERSTONE CONTENT)
-- ==============================================================================

create table if not exists public.blog_categories (
  slug varchar(120) primary key,
  title varchar(160) not null,
  description text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

insert into public.blog_categories (slug, title, description, sort_order, is_active)
values
  ('bridal', 'Bridal', 'Bridal makeup guidance, trends, and wedding day preparation.', 1, true),
  ('academy', 'Academy', 'Beauty education, training, and professional certification insights.', 2, true),
  ('skincare', 'Skincare', 'Pre-bridal, hydra facial, and barrier recovery skincare routines.', 3, true),
  ('beauty-tips', 'Beauty Tips', 'Practical everyday beauty, hair architecture, and glam tips.', 4, true)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  updated_at = now();

create table if not exists public.blog_authors (
  slug varchar(120) primary key,
  name varchar(160) not null,
  bio text,
  avatar_url varchar(255),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

insert into public.blog_authors (slug, name, bio, avatar_url, is_active)
values
  (
    'rasmirekha-swain',
    'Rasmirekha Swain',
    'Founder & Master Bridal Artist at Elegance Makeover & Academy. Over 10+ years of expertise in luxury HD, airbrush wedding styling, and beauty mentorship across Odisha.',
    '/assets/owner.webp',
    true
  )
on conflict (slug) do update set
  name = excluded.name,
  bio = excluded.bio,
  avatar_url = excluded.avatar_url,
  updated_at = now();

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug varchar(180) not null unique,
  title varchar(255) not null,
  excerpt text not null,
  content_text text not null,
  featured_image_url varchar(255),
  tags_text text,
  category_slug varchar(120) not null references public.blog_categories(slug) on update cascade on delete restrict,
  author_slug varchar(120) not null references public.blog_authors(slug) on update cascade on delete restrict,
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  seo_title varchar(255),
  seo_description text,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.blog_posts
  add column if not exists last_reviewed_at timestamptz default now(),
  add column if not exists reviewer_slug text default 'rasmirekha-swain',
  add column if not exists faq_json jsonb default '[]'::jsonb;

-- Ensure slug is unconditionally uniquely indexed for ON CONFLICT
alter table public.blog_posts drop constraint if exists blog_posts_slug_key;
drop index if exists public.idx_blog_posts_slug;
create unique index if not exists idx_blog_posts_slug on public.blog_posts (slug);

-- Upsert the 12 Cornerstone Blog Posts
insert into public.blog_posts (
  slug, title, excerpt, content_text, featured_image_url, tags_text,
  category_slug, author_slug, published_at, updated_at, last_reviewed_at,
  seo_title, seo_description, is_featured, is_published, sort_order
)
values
  (
    'bridal-makeup-cost-odisha',
    'Bridal Makeup Cost in Odisha: Complete 2026 Price Guide',
    'Comprehensive breakdown of bridal makeup pricing across Odisha, from Classic HD at ₹8,000 to Luxury Airbrush at ₹16,000, including artist travel policies.',
    $$Planning wedding expenses in Odisha requires transparency. In 2026, professional bridal makeup packages typically range from ₹6,000 to ₹18,000, determined by formulation (HD vs Airbrush), artist seniority, and venue travel distance. Signature HD bridal makeup is ₹8,000 - ₹12,000, while Airbrush packages range from ₹12,000 to ₹16,000, including luxury skin prep, 3D lashes, hair styling, Odia saree draping, and mukut placement.$$,
    'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    'bridal makeup cost Odisha,bridal makeup price Jajpur Road,HD bridal makeup rate Cuttack,airbrush bridal makeup cost Bhubaneswar',
    'bridal',
    'rasmirekha-swain',
    '2026-06-01T00:00:00Z',
    now(),
    now(),
    'Bridal Makeup Cost in Odisha | 2026 Price Guide',
    'Discover exact bridal makeup costs in Odisha. Compare HD vs Airbrush rates in Jajpur Road, Cuttack & Bhubaneswar with inclusions breakdown.',
    true,
    true,
    1
  ),
  (
    'odia-bridal-makeup-guide',
    'Odia Bridal Makeup Look: Traditions, Mukut & Saree Draping',
    'Everything you need to know about crafting an authentic Odia bridal makeover, from intricate chandan designs to royal mukut balancing.',
    $$The quintessential Odia bride embodies divine grace, tradition, and regal simplicity. Central to the Odia bridal aesthetic is the Mukut crown and delicate Chandan art framing the forehead. At Elegance Makeover, smudge-resistant waterproof liquid pigments ensure motifs remain crisp through ceremonial smoke and humidity.$$,
    'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80',
    'Odia bridal makeup,traditional Odia bride,mukut fitting Odia wedding,Odia bridal saree drape,chandan art bride',
    'bridal',
    'rasmirekha-swain',
    '2026-06-05T00:00:00Z',
    now(),
    now(),
    'Odia Bridal Makeup Look: Traditional Styling Guide',
    'Complete guide to the traditional Odia bridal look. Master mukut fitting, chandan bindi art, red sambalpuri saree draping & sweatproof bridal bases.',
    true,
    true,
    2
  ),
  (
    'hd-vs-airbrush-makeup-indian-skin',
    'HD vs Airbrush Makeup for Indian Skin Tones & Humid Climates',
    'Detailed technical comparison between High-Definition brushwork and Airbrush micro-spraying to help you choose the right base for your wedding day.',
    $$HD makeup uses micronized liquid foundations applied with dense buffing brushes for custom blendability and radiance (lasting 12-14 hours). Airbrush makeup mists microscopic silicone droplets through a precision compressor, creating a 100% waterproof, tear-resistant shield ideal for coastal Odisha humidity and 4K cameras.$$,
    'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&q=80',
    'HD vs airbrush makeup,airbrush makeup Indian skin,bridal makeup humidity Odisha,waterproof wedding makeup',
    'bridal',
    'rasmirekha-swain',
    '2026-06-10T00:00:00Z',
    now(),
    now(),
    'HD vs Airbrush Makeup for Indian Skin | Comparison',
    'Compare HD vs Airbrush makeup for Indian skin. Discover longevity, waterproof performance, camera finish, and pricing differences in Odisha.',
    true,
    true,
    3
  ),
  (
    'pre-bridal-skincare-timeline',
    'Pre-Bridal Skincare Timeline: 6-Month Countdown to Radiant Glow',
    'Achieve radiant glass skin on your wedding day with this expert month-by-month skincare and aesthetic treatment schedule.',
    $$Flawless wedding-day makeup begins months before foundation. At 6 months: consult an expert, establish AHA/BHA, vitamin C and SPF routines. At 3 months: schedule monthly Hydra Facials for vortex extraction. At 1 week: focus strictly on barrier hydration, sleep, and avoid new chemical experiments.$$,
    'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    'pre bridal skincare,wedding skincare timeline,hydra facial bride,pre bridal packages Jajpur Road',
    'skincare',
    'rasmirekha-swain',
    '2026-06-15T00:00:00Z',
    now(),
    now(),
    'Pre-Bridal Skincare Timeline | 6-Month Wedding Routine',
    'Step-by-step pre-bridal skincare schedule from 6 months to 1 week before wedding day. Facials, hydra-dermabrasion, diet tips & chemical peel warnings.',
    false,
    true,
    4
  ),
  (
    'makeup-artist-course-fees-career-odisha',
    'Makeup Artist Course Fees & Career Opportunities in Odisha',
    'Complete guide to enrolling in a certified professional makeup academy in Odisha, with realistic career pathways, tool kit investments, and earning potential.',
    $$Bridal beauty in Odisha is booming. Foundational 1-month certificates range from ₹15,000 to ₹20,000, while comprehensive 3-month Professional Bridal & Airbrush Diplomas range from ₹35,000 to ₹50,000. At Elegance Academy, students receive 100% hands-on training on live models covering base science, airbrushing, and client pricing.$$,
    'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=800&q=80',
    'makeup artist course fees Odisha,makeup academy Jajpur Road,beautician course Cuttack,bridal makeup training Bhubaneswar',
    'academy',
    'rasmirekha-swain',
    '2026-06-20T00:00:00Z',
    now(),
    now(),
    'Makeup Artist Course Fees & Career Guide in Odisha',
    'Explore professional makeup artist courses in Odisha. Learn course fees, duration, hands-on model syllabus, certification & career earnings in 2026.',
    true,
    true,
    5
  ),
  (
    'wedding-day-makeup-checklist',
    'The Ultimate Wedding-Day Makeup & Bridal Touch-Up Checklist',
    'Never forget an essential detail with this comprehensive wedding morning checklist designed specifically for Indian and Odia brides.',
    $$Morning Logistics: Start hair and makeup 4 hours prior to the Baraat arrival in a button-down shirt. Emergency Vanity Kit: pack blotting papers, sample lip color, lash glue, bobby pins, and safety pins. During mandap rituals, dab tears gently below the waterline—never wipe across the cheek.$$,
    'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    'wedding day makeup checklist,bridal emergency kit,bridal touchup tips,wedding day timeline bride',
    'bridal',
    'rasmirekha-swain',
    '2026-06-25T00:00:00Z',
    now(),
    now(),
    'Wedding-Day Makeup Checklist: Bride''s Survival Guide',
    'Essential wedding-day bridal beauty checklist for Indian brides. Timeline planning, vanity emergency kit items, and touch-up tips for the mandap.',
    false,
    true,
    6
  ),
  (
    'hairstyles-for-odia-weddings',
    'Traditional & Modern Hairstyles for Odia Weddings: Gajra & Mukut',
    'From classical low donut buns adorned with fresh mogra strings to modern cascading Hollywood waves, explore the finest bridal hair designs.',
    $$Bridal hair architecture for Odia weddings requires structural integrity to support the heavy mukut, matha patti, and veil. Classic low buns with fragrant Mogra gajra are favored for lagna, while textured floral chignons and modern waves star in evening receptions.$$,
    'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
    'Odia wedding hairstyles,bridal gajra hairstyles,bridal bun with mukut,Odia bride hairstyle Jajpur',
    'beauty-tips',
    'rasmirekha-swain',
    '2026-07-01T00:00:00Z',
    now(),
    now(),
    'Hairstyles for Odia Weddings: Gajra, Buns & Mukut',
    'Explore 8 gorgeous hairstyles for Odia brides. Discover how to style fresh jasmine gajra, anchor heavy mukuts, and create textured messy buns.',
    false,
    true,
    7
  ),
  (
    'bridal-makeup-for-all-skin-tones',
    'Bridal Makeup Guide for Oily, Dry & Dusky Indian Skin Tones',
    'How to avoid ashy bases and flash-back by matching warm golden undertones and tailoring prep for oily vs dry skin textures.',
    $$Ashy bases occur when foundation is too light or has cool pink undertones on warm golden or olive Indian skin. Custom peach and yellow color-correction balances undertones seamlessly with the collarbone. Oily skin benefits from target baking; dry complexions require deep hyaluronic moisture prep.$$,
    'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
    'bridal makeup dusky Indian skin,bridal makeup oily skin Odisha,undertone matching Indian bride,warm undertone makeup',
    'bridal',
    'rasmirekha-swain',
    '2026-07-05T00:00:00Z',
    now(),
    now(),
    'Bridal Makeup for Indian Skin Tones & Skin Types',
    'Expert undertone matching, baking techniques & foundation formulations for dusky, warm, oily, and dry Indian skin tones. Read pro tips.',
    false,
    true,
    8
  ),
  (
    'haldi-mehendi-makeup-looks',
    'Haldi & Mehendi Makeup: Waterproof Glow & Floral Aesthetics',
    'Keep your pre-wedding function looks fresh, playful, and stain-resistant with these expert Haldi and Mehendi beauty tips.',
    $$Haldi ceremonies require minimal, stain-resistant makeup. Lightweight tinted moisturizers, waterproof eyebrow pomades, and water-repellent setting sprays ensure the base survives turmeric paste and playful rituals. Mehendi nights call for glowing glass skin and boho braids with fresh floral jewels.$$,
    'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80',
    'Haldi makeup look,Mehendi bridal look,waterproof Haldi makeup,floral jewelry styling bride',
    'bridal',
    'rasmirekha-swain',
    '2026-07-10T00:00:00Z',
    now(),
    now(),
    'Haldi & Mehendi Makeup Looks: Glow & Waterproof Guide',
    'Trending Haldi and Mehendi makeover ideas. Waterproof sweat-resistant yellow-proof base, floral hair accessories, and glass skin looks.',
    false,
    true,
    9
  ),
  (
    'how-to-choose-bridal-makeup-artist-odisha',
    'How to Choose the Best Bridal Makeup Artist in Odisha: 7 Vital Factors',
    'Avoid wedding morning disasters by screening potential bridal artists across portfolio authenticity, cosmetic brands, and contract terms.',
    $$Selecting the right bridal makeup artist is critical: 1) Verify real high-resolution client videos showing natural skin texture, 2) Inquire about genuine luxury brands (Dior, MAC, Huda Beauty), 3) Confirm sanitation of brushes and disposable wands, and 4) Ensure regional experience with Odia mukuts and lagna timelines.$$,
    'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    'best makeup artist Odisha,how to choose bridal makeup artist,bridal makeup artist Jajpur Road,bridal makeup artist Cuttack',
    'beauty-tips',
    'rasmirekha-swain',
    '2026-07-15T00:00:00Z',
    now(),
    now(),
    'How to Choose Bridal Makeup Artist in Odisha | 7 Tips',
    '7 essential criteria for picking your bridal makeup artist in Odisha. Review portfolios, check genuine testimonials, verify hygiene & understand contracts.',
    false,
    true,
    10
  ),
  (
    'airbrush-bridal-makeup-step-by-step',
    'Step-by-Step Airbrush Bridal Makeup: What Happens on Your Wedding Morning',
    'A behind-the-chair look at how Master Artist Rasmirekha Swain transforms brides with micro-fine silicone airbrush compressors.',
    $$A full airbrush session follows 4 precise stages: 1) Dermal clarification and silicone barrier priming (0-25m), 2) Precision eye artistry and brow architecture prior to base work (25-65m), 3) Micro-mist compressor foundation dispersion (65-95m), and 4) Hair architecture, mukut anchoring, and saree pleating (95-180m).$$,
    'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&q=80',
    'airbrush makeup process,airbrush wedding makeup steps,airbrush compressor makeup,airbrush bridal Jajpur Road',
    'bridal',
    'rasmirekha-swain',
    '2026-07-20T00:00:00Z',
    now(),
    now(),
    'Step-by-Step Airbrush Bridal Makeup: The Experience',
    'Detailed walk-through of an HD Airbrush bridal makeup session. Discover compressor setup, silicone dispersion, eyebrow mapping, and setting.',
    false,
    true,
    11
  ),
  (
    'post-bridal-skincare-makeup-removal',
    'Post-Bridal Skincare: Safe Heavy Makeup Removal & Skin Recovery',
    'Protect your skin barrier after days of heavy wedding makeup and sacred ritual smoke with this gentle recovery protocol.',
    $$Never sleep in heavy bridal makeup. Double-cleansing is vital: 1) Soak lash glue with oil micellar water to slip lashes off gently, 2) Massage a rich cleansing balm onto dry skin for 60s to break down silicone airbrush polymers, 3) Rinse with a sulfate-free foaming cleanser, and 4) Restore skin barrier with ceramide and hyaluronic serums.$$,
    'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80',
    'how to remove bridal makeup,remove airbrush makeup,post bridal skincare,double cleansing bride',
    'skincare',
    'rasmirekha-swain',
    '2026-07-25T00:00:00Z',
    now(),
    now(),
    'Post-Bridal Skincare: Safe Makeup Removal & Recovery',
    'How to safely remove waterproof bridal and airbrush makeup without irritation. Double-cleansing methods, barrier recovery & soothing serums.',
    false,
    true,
    12
  )
on conflict (slug) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  content_text = excluded.content_text,
  featured_image_url = excluded.featured_image_url,
  tags_text = excluded.tags_text,
  category_slug = excluded.category_slug,
  author_slug = excluded.author_slug,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  is_featured = excluded.is_featured,
  is_published = excluded.is_published,
  sort_order = excluded.sort_order,
  last_reviewed_at = now(),
  updated_at = now();

drop trigger if exists trigger_blog_posts_touch_updated_at on public.blog_posts;
create trigger trigger_blog_posts_touch_updated_at
before update on public.blog_posts
for each row
execute function public.touch_updated_at();

-- ==============================================================================
-- 4. ROW-LEVEL SECURITY & PERMISSIONS
-- ==============================================================================

alter table public.services enable row level security;
alter table public.service_areas enable row level security;
alter table public.blog_categories enable row level security;
alter table public.blog_authors enable row level security;
alter table public.blog_posts enable row level security;

-- Grants for Supabase API access
grant usage on schema public to anon, authenticated, service_role;
grant select on public.services to anon, authenticated;
grant select on public.service_areas to anon, authenticated;
grant select on public.blog_categories to anon, authenticated;
grant select on public.blog_authors to anon, authenticated;
grant select on public.blog_posts to anon, authenticated;

grant all on public.services to service_role;
grant all on public.service_areas to service_role;
grant all on public.blog_categories to service_role;
grant all on public.blog_authors to service_role;
grant all on public.blog_posts to service_role;

-- Public Read Policies (idempotent block)
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'services' and policyname = 'Public can view active services'
  ) then
    create policy "Public can view active services" on public.services
      for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'service_areas' and policyname = 'Public can view active service areas'
  ) then
    create policy "Public can view active service areas" on public.service_areas
      for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'blog_categories' and policyname = 'Public can view active blog categories'
  ) then
    create policy "Public can view active blog categories" on public.blog_categories
      for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'blog_authors' and policyname = 'Public can view active blog authors'
  ) then
    create policy "Public can view active blog authors" on public.blog_authors
      for select using (is_active = true and deleted_at is null);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'blog_posts' and policyname = 'Public can view published blog posts'
  ) then
    create policy "Public can view published blog posts" on public.blog_posts
      for select using (is_published = true and deleted_at is null);
  end if;
end;
$$;
